@nonmobile
Feature: Using Android Devices Check Top UK Sites and domains

  Scenario Outline: Using Android Browse top UK sites
    Given open chrome "<url>" and check http status "<bool>"

    Examples: 
      | url                                                            | bool  |
      | https://1337x.unblocked.tv/                                    | false |
      | https://325.nostate.net/                                       | false |
      | https://420.reviews/                                           | false |
      | https://420medicated.com/                                      | false |
      | https://420time.top/                                           | false |
      | https://5starhookah.com/                                       | false |
      | https://a.manhunt.net/                                         | false |
      | https://acutforyou.livejournal.com/                            | false |
      | https://af-ex-nl-ams-5-1.northghost.com/                       | false |
      | https://affiliate.privatevpn.com/                              | false |
      | https://affiliates.vapeworld.com/                              | false |
      | https://affiliates.vpn.ht/                                     | false |
      | https://ajzu.pl/                                               | false |
      | https://akseeds.com/                                           | false |
      | https://alicecarolidotcom.wordpress.com/                       | false |
      | https://altright.com/                                          | false |
      | https://amp.planetofthevapes.co.uk/                            | false |
      | https://ancestralcult.com/                                     | false |
      | https://animalliberationpressoffice.org/                       | false |
      | https://anti-antifagear.net/                                   | false |
      | https://api.dankstop.com/                                      | false |
      | https://api.trybaker.com/                                      | false |
      | https://app.massroots.com/                                     | false |
      | https://aslashabove.com/                                       | false |
      | https://assets.smokingpipes.com/                               | false |
      | https://azelin.files.wordpress.com/                            | false |
      | https://bateworld.com/                                         | false |
      | https://bcbud.store/                                           | false |
      | https://bee-high.com/                                          | false |
      | https://bestbudbags.com/                                       | false |
      | https://bestcigliquid.co.uk/                                   | false |
      | https://billowby.com/                                          | false |
      | https://blog.hackersonlineclub.com/                            | false |
      | https://blog.ipvanish.com/                                     | false |
      | https://bloody-disgusting.com/                                 | false |
      | https://bobhq.com/                                             | false |
      | https://bognorregis.2day.uk/                                   | false |
      | https://bookstore.autonomedia.org/                             | false |
      | https://braciasamcy.pl/                                        | false |
      | https://brfoundersblog.com/                                    | false |
      | https://brotherswithglass.com/                                 | false |
      | https://bulimicbible.wordpress.com/                            | false |
      | https://business.massroots.com/                                | false |
      | https://buyweedonline.ca/                                      | false |
      | https://canamo.cl/                                             | false |
      | https://cannabisdigest.ca/                                     | false |
      | https://cannabisgrowing.wordpress.com/                         | false |
      | https://cannabissocialclubtenerife.wordpress.com/              | false |
      | https://cannabisspain.wordpress.com/                           | false |
      | https://cannador.com/                                          | false |
      | https://carder007.net/                                         | false |
      | https://carolynyeager.net/                                     | false |
      | https://cbdgum.networkofhemp.com/                              | false |
      | https://cc.greatfire.org/                                      | false |
      | https://cdn-video.dieselaccess.com/                            | false |
      | https://cdn.darknet.org.uk/                                    | false |
      | https://cdn.learntohack.co.uk/                                 | false |
      | https://cdn.vapeworld.com/                                     | false |
      | https://cdn.weednews.co/                                       | false |
      | https://cdn.zeusclicks.com/                                    | false |
      | https://cdnlw2.pichaloca.com/                                  | false |
      | https://cdnlw3.pichaloca.com/                                  | false |
      | https://cdnlw4.pichaloca.com/                                  | false |
      | https://celticvapours.com/                                     | false |
      | https://centurean2.wordpress.com/                              | false |
      | https://chechar.wordpress.com/                                 | false |
      | https://chewygrinder.com/                                      | false |
      | https://chinglabs.com/                                         | false |
      | https://cityseedsbank.com/                                     | false |
      | https://codoh.com/                                             | false |
      | https://coffeeshopsamsterdam.com/                              | false |
      | https://cons.wonderhowto.com/                                  | false |
      | https://cornerstonecollective.com/                             | false |
      | https://crazymass.com/                                         | false |
      | https://crazyvapors.com/                                       | false |
      | https://cvv-me.su/                                             | false |
      | https://cvvshop.lv/                                            | false |
      | https://dankgeek.com/                                          | false |
      | https://darkheartnursery.com/                                  | false |
      | https://davidduke.com/                                         | false |
      | https://dawaalhaq.com/                                         | false |
      | https://deliandiver.org/                                       | false |
      | https://delivery.manhunt.net/                                  | false |
      | https://delta3dstudios.com/                                    | false |
      | https://desertpeace.wordpress.com/                             | false |
      | https://dev.metasploit.com/                                    | false |
      | https://dev.purduehemp.org/                                    | false |
      | https://dividerpro.com/                                        | false |
      | https://do-ex-de-17.northghost.com/                            | false |
      | https://do-ex-de-19.northghost.com/                            | false |
      | https://do-ex-de-22.northghost.com/                            | false |
      | https://do-ex-de-8.northghost.com/                             | false |
      | https://do-ex-gb-11.northghost.com/                            | false |
      | https://do-ex-gb-4.northghost.com/                             | false |
      | https://do-ex-gb-6.northghost.com/                             | false |
      | https://do-ex-gb-8.northghost.com/                             | false |
      | https://do-ex-in-6.northghost.com/                             | false |
      | https://do-ex-in-8.northghost.com/                             | false |
      | https://do-ex-us-ny-5.northghost.com/                          | false |
      | https://doctorfrank.com/                                       | false |
      | https://doobdasher.com/                                        | false |
      | https://dropping-seeds.com/                                    | false |
      | https://drugsforum.nl/                                         | false |
      | https://eatprayliveblog.wordpress.com/                         | false |
      | https://ecigwizard.com/                                        | false |
      | https://elementalwellnesscenter.com/                           | false |
      | https://elixinolcbd.com/                                       | false |
      | https://embed.getmeadow.com/                                   | false |
      | https://energycontrol.org/                                     | false |
      | https://english.palinfo.com/                                   | false |
      | https://enoughisenough14.org/                                  | false |
      | https://ensobotanicals.com/                                    | false |
      | https://enterprise55.fastsecurehost.com/                       | false |
      | https://ethnikismos.net/                                       | false |
      | https://eve-rave.ch/                                           | false |
      | https://evilsocket.net/                                        | false |
      | https://exiteuthanasia.wordpress.com/                          | false |
      | https://exitinternational.net/                                 | false |
      | https://exploit-db.com/                                        | false |
      | https://exposingfeminism.wordpress.com/                        | false |
      | https://extratorrent.unblocked.live/                           | false |
      | https://extremepeptides.com/                                   | false |
      | https://extremesupporters.com/                                 | false |
      | https://eztrimming.com/                                        | false |
      | https://fakeidentification.co.uk/                              | false |
      | https://farmerslabseeds.com/                                   | false |
      | https://finetofab.com/                                         | false |
      | https://fitisafeministissue.com/                               | false |
      | https://fldispensaries.com/                                    | false |
      | https://flmmcc.com/                                            | false |
      | https://floridamarijuanainfo.org/                              | false |
      | https://formobile.com.au/                                      | false |
      | https://forum.codoh.com/                                       | false |
      | https://forum.totallywicked-eliquid.com/                       | false |
      | https://forums.5meodmt.org/                                    | false |
      | https://fr.novopress.info/                                     | false |
      | https://friproxy0.biz/                                         | false |
      | https://fuhrerious88blog.wordpress.com/                        | false |
      | https://funguidetoamsterdam.wordpress.com/                     | false |
      | https://furtherglory.wordpress.com/                            | false |
      | https://futurolausa.com/                                       | false |
      | https://g43s4nztfy3dolrrgu2sgmjvga2dknrzgyyda.cd-n.net/        | false |
      | https://gatesofvienna.net/                                     | false |
      | https://gaylor-moon.tumblr.com/                                | false |
      | https://ge4dklrygyxdcnbyfy2dqizrguydimzzgy4dama.cd-n.net/      | false |
      | https://ge4dklrygyxdcnbzfyytsobdge2tanbvgy4tmmbq.cd-n.net/     | false |
      | https://gekiura.com/                                           | false |
      | https://gendertrender.wordpress.com/                           | false |
      | https://gentlemansvapes.com/                                   | false |
      | https://get.betternet.co/                                      | false |
      | https://geti2p.net/                                            | false |
      | https://gettingthinsoon.wordpress.com/                         | false |
      | https://geztqlrrhe3s4mjzguxdsmbdge2tanbvgy4tmmbq.cd-n.net/     | false |
      | https://girlmodelskinny.weebly.com/                            | false |
      | https://gloucesterhydroponics.wordpress.com/                   | false |
      | https://goddessdelivers.com/                                   | false |
      | https://goregrish.com/                                         | false |
      | https://greendoorwest.com/                                     | false |
      | https://greenly.me/                                            | false |
      | https://greenvapes.co.uk/                                      | false |
      | https://greenz.ca/                                             | false |
      | https://grizzlyoriginals.com/                                  | false |
      | https://grower.com.pl/                                         | false |
      | https://growguide.opengrow.com/                                | false |
      | https://growlightcentral.com/                                  | false |
      | https://guyhumor.tv/                                           | false |
      | https://hackmii.com/                                           | false |
      | https://halcyonorganics.com/                                   | false |
      | https://hashcat.net/                                           | false |
      | https://havetobeskinny.wordpress.com/                          | false |
      | https://headshop.ee/                                           | false |
      | https://hellhorror.com/                                        | false |
      | https://hempture.ie/                                           | false |
      | https://henrymakow.com/                                        | false |
      | https://highgradeaid.com/                                      | false |
      | https://hls.nakednewscdn.com/                                  | false |
      | https://holocaustdeprogrammingcourse.com/                      | false |
      | https://horux.ru/                                              | false |
      | https://hotguysfuck.com/                                       | false |
      | https://houseofmysterioussecrets.com/                          | false |
      | https://howtogrowbigbuds.wordpress.com/                        | false |
      | https://humboldt-traders.com/                                  | false |
      | https://hwnds.ddfstatic.com/                                   | false |
      | https://hybridsfromhell.net/                                   | false |
      | https://ibudtender.com/                                        | false |
      | https://icut.livejournal.com/                                  | false |
      | https://ilovekratom.com/                                       | false |
      | https://images.adam4adam.com/                                  | false |
      | https://images.eroticbeauties.net/                             | false |
      | https://images.vapouriz.co.uk/                                 | false |
      | https://img.hackhome.com/                                      | false |
      | https://img.tnastatic.com/                                     | false |
      | https://img.xn----7sbbpcak2aq2c1d.com/                         | false |
      | https://img1.tnastatic.com/                                    | false |
      | https://img11.warez-bb.org/                                    | false |
      | https://img12.pixhost.org/                                     | false |
      | https://img12.warez-bb.org/                                    | false |
      | https://img2.hackhome.com/                                     | false |
      | https://img2.tnastatic.com/                                    | false |
      | https://img3.hackhome.com/                                     | false |
      | https://img3.tnastatic.com/                                    | false |
      | https://imgcdn.datezone.com/                                   | false |
      | https://intake.getmeadow.com/                                  | false |
      | https://iriecbd.com/                                           | false |
      | https://irishvape.com/                                         | false |
      | https://islamreview.com/                                       | false |
      | https://ismokeshop.co.uk/                                      | false |
      | https://israelect.com/                                         | false |
      | https://ivapour.co.uk/                                         | false |
      | https://iwatchonline.unblocked.pw/                             | false |
      | https://j0.wlmediahub.com/                                     | false |
      | https://j4mb.org.uk/                                           | false |
      | https://jacekmiedlar.pl/                                       | false |
      | https://johnnyapplecbd.com/                                    | false |
      | https://jsansoye.wordpress.com/                                | false |
      | https://kafircrusaders.wordpress.com/                          | false |
      | https://kaotic.com/                                            | false |
      | https://kickass.unblocked.tv/                                  | false |
      | https://kids.disconnect.me/                                    | false |
      | https://kingsofkushco.com/                                     | false |
      | https://konopnysklep.com.pl/                                   | false |
      | https://kratomystic.com/                                       | false |
      | https://kurtcobainssuicidenote.com/                            | false |
      | https://kuruc.info/                                            | false |
      | https://kushcargo.com/                                         | false |
      | https://l33t.su/                                               | false |
      | https://landoverbaptist.net/                                   | false |
      | https://lastchanceshot.tumblr.com/                             | false |
      | https://leafandoil.co.uk/                                      | false |
      | https://leafist.com/                                           | false |
      | https://learnpot.blogspot.co.uk/                               | false |
      | https://learnpot.blogspot.com/                                 | false |
      | https://learntohack.co.uk/                                     | false |
      | https://ledgrowlightsexpert.com/                               | false |
      | https://libertygb.org.uk/                                      | false |
      | https://limonov-eduard.livejournal.com/                        | false |
      | https://linxvapor.com/                                         | false |
      | https://littlebiggy.com/                                       | false |
      | https://livechat.ivpn.net/                                     | false |
      | https://lookism.net/                                           | false |
      | https://lq.fuckup.xxx/                                         | false |
      | https://lushledlighting.com/                                   | false |
      | https://m.hackhome.com/                                        | false |
      | https://m.kuruc.info/                                          | false |
      | https://m.vapestick.co.uk/                                     | false |
      | https://magento.mtlotz.com/                                    | false |
      | https://magictrufflesshop.wordpress.com/                       | false |
      | https://mail.totallywicked-eliquid.co.uk/                      | false |
      | https://majorityrights.com/                                    | false |
      | https://manicbotanix.com/                                      | false |
      | https://marijuanapatients.org/                                 | false |
      | https://marshmallowfluffwoman.tumblr.com/                      | false |
      | https://maxqualityglass.com/                                   | false |
      | https://media.eroticbeauties.net/                              | false |
      | https://media.myindianporn.com/                                | false |
      | https://media01-lust.playfoul.com/                             | false |
      | https://media02-lust.playfoul.com/                             | false |
      | https://mediweed.com/                                          | false |
      | https://metrics.cannasos.com/                                  | false |
      | https://mikepiperreport.com/                                   | false |
      | https://milo.yiannopoulos.net/                                 | false |
      | https://miptj.hackhome.com/                                    | false |
      | https://missanamia.wordpress.com/                              | false |
      | https://mmpconnect.com/                                        | false |
      | https://mn.wordpress.com/                                      | false |
      | https://moringamutual.com/                                     | false |
      | https://movcdn.datezone.com/                                   | false |
      | https://mychronicrelief.com/                                   | false |
      | https://mycotek.org/                                           | false |
      | https://nationalcompassion.ca/                                 | false |
      | https://newsletters.planetofthevapes.co.uk/                    | false |
      | https://newswithviews.com/                                     | false |
      | https://nmap.org/                                              | false |
      | https://nolavape.com/                                          | false |
      | https://nordfront.se/                                          | false |
      | https://nsm88records.com/                                      | false |
      | https://oldschoolba.com/                                       | false |
      | https://opioids.com/                                           | false |
      | https://ordergreenbox.com/                                     | false |
      | https://packetstormsecurity.com/                               | false |
      | https://palinfo.com/                                           | false |
      | https://patients4medicalmarijuana.wordpress.com/               | false |
      | https://pentestmag.com/                                        | false |
      | https://peptidesdirect.com.au/                                 | false |
      | https://pics.wikifeet.com/                                     | false |
      | https://pillsforsaleonline.org/                                | false |
      | https://pipesmokersforum.com/                                  | false |
      | https://piwik.endoca.com/                                      | false |
      | https://platinum-e-liquid.com/                                 | false |
      | https://please.hackmii.com/                                    | false |
      | https://pluscbdoil.com/                                        | false |
      | https://potvalet.com/                                          | false |
      | https://powiew.com/                                            | false |
      | https://praguepot.files.wordpress.com/                         | false |
      | https://premiumpurecbd.com/                                    | false |
      | https://primalbrands.com/                                      | false |
      | https://productiongrower.com/                                  | false |
      | https://psychedelicpress.co.uk/                                | false |
      | https://purecbdvapors.com/                                     | false |
      | https://radicalhubarchives.wordpress.com/                      | false |
      | https://ragdolleatenbyunderland.wordpress.com/                 | false |
      | https://rainbow-ginger-butterfly.tumblr.com/                   | false |
      | https://rarbg.unblocked.pw/                                    | false |
      | https://razzleton.com/                                         | false |
      | https://rcnetchemicals.com/                                    | false |
      | https://re-stash.com/                                          | false |
      | https://rebel88.com/                                           | false |
      | https://rent.men/                                              | false |
      | https://researchchemicals.biz/                                 | false |
      | https://ripostelaique.com/                                     | false |
      | https://robertsdirect.co.uk/                                   | false |
      | https://rpc-php.trafficfactory.biz/                            | false |
      | https://rue-morgue.com/                                        | false |
      | https://safervpn.com/                                          | false |
      | https://scams.wikispaces.com/                                  | false |
      | https://sd.fuckup.xxx/                                         | false |
      | https://sea1c-ls.naiadsystems.com/                             | false |
      | https://securepubads.g.doubleclick.net.prx.proxyunblocker.org/ | false |
      | https://securityonline.info/                                   | false |
      | https://self-injury.net/                                       | false |
      | https://selfuni.wordpress.com/                                 | false |
      | https://serials.ws/                                            | false |
      | https://setmyip.trustedproxies.com/                            | false |
      | https://shattershack.ca/                                       | false |
      | https://shop-lifestyles.com/                                   | false |
      | https://shop.codoh.com/                                        | false |
      | https://shop.planetofthevapes.co.uk/                           | false |
      | https://showard76.wordpress.com/                               | false |
      | https://sistersofcbd.com/                                      | false |
      | https://skins2you.com/                                         | false |
      | https://sky-fraud.ru/                                          | false |
      | https://slimambition.wordpress.com/                            | false |
      | https://smoke-box.com/                                         | false |
      | https://smokersheaven.com/                                     | false |
      | https://snuscentral.org/                                       | false |
      | https://softwarestab.com/                                      | false |
      | https://somethinggprofound.wordpress.com/                      | false |
      | https://spaceapi.fixme.ch/                                     | false |
      | https://ss-cdn.femjoy.com/                                     | false |
      | https://ss.l33t.su/                                            | false |
      | https://stat.cannasos.com/                                     | false |
      | https://static.weedy.com/                                      | false |
      | https://stats.ivpn.net/                                        | false |
      | https://stats.suck-o.com/                                      | false |
      | https://stavvers.wordpress.com/                                | false |
      | https://stealthgrowbox.co.uk/                                  | false |
      | https://steroids-2016.com/                                     | false |
      | https://stokedct.com/                                          | false |
      | https://stopsyjonizmowi.wordpress.com/                         | false |
      | https://stream.flixtor.live/                                   | false |
      | https://suicideproject.org/                                    | false |
      | https://support.betternet.co/                                  | false |
      | https://support.jacvapour.com/                                 | false |
      | https://support.vapes.com/                                     | false |
      | https://svn.nmap.org/                                          | false |
      | https://synergycbd.com/                                        | false |
      | https://terriblelinuxwallpaper.tumblr.com/                     | false |
      | https://thcustompromos.com/                                    | false |
      | https://thebritishseedcompany.co.uk/                           | false |
      | https://thecoffeeshops.com/                                    | false |
      | https://thedablab.com/                                         | false |
      | https://theendofzion.com/                                      | false |
      | https://thefappening.wiki/                                     | false |
      | https://thefarmco.com/                                         | false |
      | https://thefatworddotcom.files.wordpress.com/                  | false |
      | https://thegreateststorynevertold.tv/                          | false |
      | https://thegreenrhino.ca/                                      | false |
      | https://thehedonistclub.co.uk/                                 | false |
      | https://thehempchronicle.com/                                  | false |
      | https://thehighcan.com/                                        | false |
      | https://thehotboxmagazine.com/                                 | false |
      | https://themuslimissue.wordpress.com/                          | false |
      | https://thepirateportal.net/                                   | false |
      | https://therealseedcompany.com/                                | false |
      | https://thespanofmyhips.wordpress.com/                         | false |
      | https://theuglytruth.wordpress.com/                            | false |
      | https://thevespiary.org/                                       | false |
      | https://thezog.wordpress.com/                                  | false |
      | https://thisiseuropa.net/                                      | false |
      | https://thrivenevada.com/                                      | false |
      | https://thuleanperspective.com/                                | false |
      | https://thumbs.wikifeet.com/                                   | false |
      | https://tj.hackhome.com/                                       | false |
      | https://toastick.wordpress.com/                                | false |
      | https://tokecity.com/                                          | false |
      | https://toool.us/                                              | false |
      | https://topshelf.webjoint.com/                                 | false |
      | https://torrenthound.unblocked.pw/                             | false |
      | https://totseans.com/                                          | false |
      | https://trees.chat/                                            | false |
      | https://tripsafe.org/                                          | false |
      | https://trustedproxies.com/                                    | false |
      | https://tubeunblock.com/                                       | false |
      | https://uglymeskin19.files.wordpress.com/                      | false |
      | https://uk-ln-001.privatetunnel.com/                           | false |
      | https://uk.quickfixurine.com/                                  | false |
      | https://uklocksport.co.uk/                                     | false |
      | https://ukvapers.org/                                          | false |
      | https://understandmagicmushrooms.wordpress.com/                | false |
      | https://unicc.at/                                              | false |
      | https://unikatowebonga.pl/                                     | false |
      | https://uppercanadaseedbank.ca/                                | false |
      | https://vapenewsmagazine.com/                                  | false |
      | https://vapeoutlet.co/                                         | false |
      | https://vapestore.co.za/                                       | false |
      | https://vapevetstore.com/                                      | false |
      | https://videos.deathaddict.com/                                | false |
      | https://violenceagainstwhites.wordpress.com/                   | false |
      | https://vipelectroniccigarette.co.uk/                          | false |
      | https://vnnforum.com/                                          | false |
      | https://voxnews.info/                                          | false |
      | https://vpn.ht/                                                | false |
      | https://vpntunnel.com/                                         | false |
      | https://w.drugs-forum.co/                                      | false |
      | https://weedy.com/                                             | false |
      | https://welfareatmarys.files.wordpress.com/                    | false |
      | https://whitelocust.wordpress.com/                             | false |
      | https://wholesale.thehookah.com/                               | false |
      | https://whyeat.net/                                            | false |
      | https://wiki.cannaweed.com/                                    | false |
      | https://wincest-recs.livejournal.com/                          | false |
      | https://witchwind.wordpress.com/                               | false |
      | https://wolnekonopie.org/                                      | false |
      | https://writing-with-a-blade.tumblr.com/                       | false |
      | https://www.420chan.org/                                       | false |
      | https://www.alipac.us/                                         | false |
      | https://www.alphapuff.com/                                     | false |
      | https://www.americasfreedomfighters.com/                       | false |
      | https://www.amren.com/                                         | false |
      | https://www.armyofgod.com/                                     | false |
      | https://www.backtrack-linux.org/                               | false |
      | https://www.bestcigliquid.co.uk/                               | false |
      | https://www.bestgore.com/                                      | false |
      | https://www.bestvpnserver.com/                                 | false |
      | https://www.bismark.it/                                        | false |
      | https://www.bitchyourfamous.com/                               | false |
      | https://www.blackleaf.de/                                      | false |
      | https://www.bluelips.com/                                      | false |
      | https://www.bongoutlet.com/                                    | false |
      | https://www.bongs.co.uk/                                       | false |
      | https://www.botanicalspirit.com/                               | false |
      | https://www.bpong.com/                                         | false |
      | https://www.brc-finechemicals.com/                             | false |
      | https://www.brhfulfillment.com/                                | false |
      | https://www.bronzedpeptides.com/                               | false |
      | https://www.brotherhoodofpain.com/                             | false |
      | https://www.budbardisplays.com/                                | false |
      | https://www.buyhappyglass.com/                                 | false |
      | https://www.buypassportsfake.cc/                               | false |
      | https://www.californiamarijuanadelivery.com/                   | false |
      | https://www.calikushstore.com/                                 | false |
      | https://www.caliweedexpress.com/                               | false |
      | https://www.cannageneticsbank.com/                             | false |
      | https://www.cannasaver.com/                                    | false |
      | https://www.cannastick.com/                                    | false |
      | https://www.cannimed.ca/                                       | false |
      | https://www.carder007.net/                                     | false |
      | https://www.cbd-vape.co.uk/                                    | false |
      | https://www.cbdbureau.com/                                     | false |
      | https://www.celticvapours.com/                                 | false |
      | https://www.cheap-mdpv.com/                                    | false |
      | https://www.christianophobie.fr/                               | false |
      | https://www.cigarpass.com/                                     | false |
      | https://www.cloud9vaping.co.uk/                                | false |
      | https://www.cloudstix.com/                                     | false |
      | https://www.coffeeshop.tours/                                  | false |
      | https://www.coffeeshopibiza.com/                               | false |
      | https://www.coffeeshopsamsterdam.com/                          | false |
      | https://www.counter-currents.com/                              | false |
      | https://www.cscctfs.com/                                       | false |
      | https://www.cubancigarwebsite.com/                             | false |
      | https://www.cvvshop.lv/                                        | false |
      | https://www.dankofcanada.com/                                  | false |
      | https://www.dappercadaver.com/                                 | false |
      | https://www.darkmoon.me/                                       | false |
      | https://www.darknet.org.uk/                                    | false |
      | https://www.dc-unlocker.com/                                   | false |
      | https://www.deathwithdignity.org/                              | false |
      | https://www.dekratomshop.nl/                                   | false |
      | https://www.detoxforless.com/                                  | false |
      | https://www.diplomacompany.com/                                | false |
      | https://www.disinformazione.it/                                | false |
      | https://www.dispensaries.com/                                  | false |
      | https://www.documentingreality.com/                            | false |
      | https://www.dopeboo.com/                                       | false |
      | https://www.drinkiwiki.com/                                    | false |
      | https://www.dutch-smart.nl/                                    | false |
      | https://www.dutchfem.com/                                      | false |
      | https://www.e-cigarette-forum.com/                             | false |
      | https://www.e-lites.co.uk/                                     | false |
      | https://www.ecigarettedirect.co.uk/                            | false |
      | https://www.ecigology.com/                                     | false |
      | https://www.ecigwizard.com/                                    | false |
      | https://www.eliquidlabs.co.uk/                                 | false |
      | https://www.eliquidworld.co.uk/                                | false |
      | https://www.emeraldharvest.co/                                 | false |
      | https://www.eppinghydroponics.com.au/                          | false |
      | https://www.erodate.pl/                                        | false |
      | https://www.essencehealing.co/                                 | false |
      | https://www.estagecraft.com/                                   | false |
      | https://www.ethicalrights.com/                                 | false |
      | https://www.evilsocket.net/                                    | false |
      | https://www.exploit-db.com/                                    | false |
      | https://www.extremefreegames.com/                              | false |
      | https://www.faithfreedom.org/                                  | false |
      | https://www.fakeid.co.uk/                                      | false |
      | https://www.fakeidentification.co.uk/                          | false |
      | https://www.fatmanseeds.co.uk/                                 | false |
      | https://www.findaheadshop.com/                                 | false |
      | https://www.firestaxusa.com/                                   | false |
      | https://www.flavourvapour.co.uk/                               | false |
      | https://www.flowkana.com/                                      | false |
      | https://www.friendsofhabanos.com/                              | false |
      | https://www.funkypiece.com/                                    | false |
      | https://www.gayties.com/                                       | false |
      | https://www.get-rc.to/                                         | false |
      | https://www.getmyster.com/                                     | false |
      | https://www.getsava.com/                                       | false |
      | https://www.gr8researchchemicals-eu.com/                       | false |
      | https://www.grizzlyoriginals.com/                              | false |
      | https://www.grovida.us/                                        | false |
      | https://www.grower.ch/                                         | false |
      | https://www.guide-coffeeshops.com/                             | false |
      | https://www.guysway.co.uk/                                     | false |
      | https://www.hackersportugal.com/                               | false |
      | https://www.hackhome.com/                                      | false |
      | https://www.hacking.pl/                                        | false |
      | https://www.hackthissite.org/                                  | false |
      | https://www.hasmoke.com/                                       | false |
      | https://www.hatebreed.com/                                     | false |
      | https://www.head-shop.eu/                                      | false |
      | https://www.healthyhempoil.com/                                | false |
      | https://www.heathersheavenlyvapes.com/                         | false |
      | https://www.hempcompany.ie/                                    | false |
      | https://www.hempfarm.co.nz/                                    | false |
      | https://www.henrymakow.com/                                    | false |
      | https://www.herbalhighs.co.uk/                                 | false |
      | https://www.herbiespicknmixseeds.com/                          | false |
      | https://www.hippiebutler.com/                                  | false |
      | https://www.hookah-shisha.com/                                 | false |
      | https://www.hookah.org/                                        | false |
      | https://www.horrorchannel.com/                                 | false |
      | https://www.horrorsociety.com/                                 | false |
      | https://www.horrortalk.com/                                    | false |
      | https://www.illicitencounters.com/                             | false |
      | https://www.incensesupreme.com/                                | false |
      | https://www.infinitevapour.com/                                | false |
      | https://www.insecure.ws/                                       | false |
      | https://www.islam-watch.org/                                   | false |
      | https://www.issoebizarro.com/                                  | false |
      | https://www.iwannagrowshop.com/                                | false |
      | https://www.jacvapour.com/                                     | false |
      | https://www.jeremiahproject.com/                               | false |
      | https://www.jesus-is-lord.com/                                 | false |
      | https://www.kaotic.com/                                        | false |
      | https://www.kingofcbdgenetics.com/                             | false |
      | https://www.kiwiland.com/                                      | false |
      | https://www.koksa.org/                                         | false |
      | https://www.konopnymarket.pl/                                  | false |
      | https://www.kushandkind.com/                                   | false |
      | https://www.ladybud.com/                                       | false |
      | https://www.landoverbaptist.net/                               | false |
      | https://www.leafandoil.co.uk/                                  | false |
      | https://www.liberty-flights.co.uk/                             | false |
      | https://www.libertygb.org.uk/                                  | false |
      | https://www.lizardjuice.com/                                   | false |
      | https://www.lockpickingfrance.org/                             | false |
      | https://www.lockpickingstore.de/                               | false |
      | https://www.lockpickshop.com/                                  | false |
      | https://www.loudmouthnews.com/                                 | false |
      | https://www.masterdamrollingsupplies.com/                      | false |
      | https://www.mcchrystals.co.uk/                                 | false |
      | https://www.metasploit.com/                                    | false |
      | https://www.michelledastier.com/                               | false |
      | https://www.midnighttoke.com/                                  | false |
      | https://www.misteliquid.co.uk/                                 | false |
      | https://www.mister-e-liquid.com/                               | false |
      | https://www.monroeblvd.com/                                    | false |
      | https://www.mtlotz.com/                                        | false |
      | https://www.mutualist.org/                                     | false |
      | https://www.myproana.com/                                      | false |
      | https://www.myshishapen.co.uk/                                 | false |
      | https://www.myxedup.com/                                       | false |
      | https://www.nabiblackseedoil.com/                              | false |
      | https://www.nelsonpotorium.ca/                                 | false |
      | https://www.newswithviews.com/                                 | false |
      | https://www.newvape.com/                                       | false |
      | https://www.noisejournal.com/                                  | false |
      | https://www.nordfront.se/                                      | false |
      | https://www.nulled.cc/                                         | false |
      | https://www.opioids.com/                                       | false |
      | https://www.organicalbotanicals.com/                           | false |
      | https://www.palinfo.com/                                       | false |
      | https://www.palscollective.com/                                | false |
      | https://www.passyourdrugtest.com.au/                           | false |
      | https://www.pdfunlock.com/                                     | false |
      | https://www.pen-cig.co.uk/                                     | false |
      | https://www.phantomplate.com/                                  | false |
      | https://www.phreak.co.uk/                                      | false |
      | https://www.pier420.com/                                       | false |
      | https://www.planete-sfactory.com/                              | false |
      | https://www.planetofthevapes.co.uk/                            | false |
      | https://www.plaor.biz/                                         | false |
      | https://www.politicalislam.com/                                | false |
      | https://www.portlandfellowship.com/                            | false |
      | https://www.potbox.com/                                        | false |
      | https://www.potvalet.com/                                      | false |
      | https://www.primevapor.com/                                    | false |
      | https://www.psytube.net/                                       | false |
      | https://www.quitbingeeating.com/                               | false |
      | https://www.returnofkings.com/                                 | false |
      | https://www.revisionisthistory.org/                            | false |
      | https://www.rollbud.com/                                       | false |
      | https://www.rollyourownpapers.com/                             | false |
      | https://www.rue-morgue.com/                                    | false |
      | https://www.ruffhousestudios.com/                              | false |
      | https://www.sacconfidential.com/                               | false |
      | https://www.safervpn.com/                                      | false |
      | https://www.serials.be/                                        | false |
      | https://www.serials.ws/                                        | false |
      | https://www.shopharborside.com/                                | false |
      | https://www.simplyeliquid.co.uk/                               | false |
      | https://www.skinnygossip.com/                                  | false |
      | https://www.skycig.co.uk/                                      | false |
      | https://www.skylighter.com/                                    | false |
      | https://www.smokestyle.org/                                    | false |
      | https://www.smoking-hookah.com/                                | false |
      | https://www.smokingfeelsgood.com/                              | false |
      | https://www.smokingpipes.com/                                  | false |
      | https://www.snuscentral.org/                                   | false |
      | https://www.solcbd.com/                                        | false |
      | https://www.soldierx.com/                                      | false |
      | https://www.southsmoke.com/                                    | false |
      | https://www.spacegrinders.com/                                 | false |
      | https://www.sploofybrand.com/                                  | false |
      | https://www.spytector.com/                                     | false |
      | https://www.sqmonitor.com/                                     | false |
      | https://www.suicideforum.com/                                  | false |
      | https://www.thcmag.com/                                        | false |
      | https://www.thctalk.com/                                       | false |
      | https://www.thcustompromos.com/                                | false |
      | https://www.thealchemistscupboard.co.uk/                       | false |
      | https://www.thebulldog.com/                                    | false |
      | https://www.thecoffeeshops.com/                                | false |
      | https://www.theelectroniccigarette.co.uk/                      | false |
      | https://www.thehookah.com/                                     | false |
      | https://www.theoriginalresinator.com/                          | false |
      | https://www.theshishashop.com/                                 | false |
      | https://www.thesmokersclub.com/                                | false |
      | https://www.thetruthseeker.co.uk/                              | false |
      | https://www.thevaporhut.com/                                   | false |
      | https://www.thickassglass.com/                                 | false |
      | https://www.tog.ie/                                            | false |
      | https://www.toro-imports.com/                                  | false |
      | https://www.totaleliquid.co.uk/                                | false |
      | https://www.totallywicked-eliquid.co.uk/                       | false |
      | https://www.totallywicked-eliquid.com/                         | false |
      | https://www.troma.com/                                         | false |
      | https://www.ultimatedetox.co.uk/                               | false |
      | https://www.unblocknetflix.co.uk/                              | false |
      | https://www.undergroundnews.com/                               | false |
      | https://www.unlockitnow.com/                                   | false |
      | https://www.unzensuriert.at/                                   | false |
      | https://www.vapeitnow.com/                                     | false |
      | https://www.vapepartsmart.com/                                 | false |
      | https://www.vapes.com/                                         | false |
      | https://www.vapestick.co.uk/                                   | false |
      | https://www.vapetime.co.uk/                                    | false |
      | https://www.vapeworld.com/                                     | false |
      | https://www.vapingliquid.com/                                  | false |
      | https://www.vapingmad.com.au/                                  | false |
      | https://www.vapingzone.com/                                    | false |
      | https://www.vapor-z.co.uk/                                     | false |
      | https://www.vapor4life.com/                                    | false |
      | https://www.vaportalk.com/                                     | false |
      | https://www.vapouriz.co.uk/                                    | false |
      | https://www.vapourmate.co.uk/                                  | false |
      | https://www.vastarinta.com/                                    | false |
      | https://www.vipelectroniccigarette.co.uk/                      | false |
      | https://www.viper-vape.com/                                    | false |
      | https://www.voc-nederland.org/                                 | false |
      | https://www.water-bongs-glass-pipes.com/                       | false |
      | https://www.weednews.co/                                       | false |
      | https://www.weedonlineus.com/                                  | false |
      | https://www.weedshops.com/                                     | false |
      | https://www.wellspringcbd.com/                                 | false |
      | https://www.whaxy.com/                                         | false |
      | https://www.wikifeet.com/                                      | false |
      | https://www.wintersonnenwende.com/                             | false |
      | https://www.withoutakey.co.uk/                                 | false |
      | https://www.wordpress.hempcompany.ie/                          | false |
      | https://www.zeitenschrift.com/                                 | false |
      | https://xakep.ru/                                              | false |
      | https://ximage.me/                                             | false |
      | https://xiosin.com/                                            | false |
      | https://xploitz.net/                                           | false |
      | https://yiannopoulos.net/                                      | false |
      | https://yts.unblocked.live/                                    | false |
      | https://zastopujczas.pl/                                       | false |
      | https://zionistreport.com/                                     | false |
      | https://zipfiles-cdn.femjoy.com/                               | false |
      | https://zvraceny.cz/                                           | false |