@nonmobile
Feature: Using Android Devices Check Top UK Sites and domains

  Scenario Outline: Using Android Browse top UK sites
    Given open chrome "<url>" and check http status "<bool>"

    Examples: 
      | url                                                                                  | bool |
      | https://www.channel4learning.net/                                                    | true |
      | https://www.dialaphone.co.uk/                                                        | true |
      | https://www.britkid.org/                                                             | true |
      | https://www.theaward.org/                                                            | true |
      | https://www.unicef.org/                                                              | true |
      | https://www.childline.org.uk/                                                        | true |
      | https://www.kettering.gov.uk/                                                        | true |
      | https://www.btbetterworld.com/                                                       | true |
      | https://www.getnetwise.org/                                                          | true |
      | https://www.girlguiding.org.uk/                                                      | true |
      | https://www.lancsngfl.ac.uk/                                                         | true |
      | https://www.yahoo.com/                                                               | true |
      | https://www.bornfree.org.uk/                                                         | true |
      | https://www.neighbours.com/                                                          | true |
      | https://www.newi.ac.uk/                                                              | true |
      | https://www.metoffice.gov.uk/                                                        | true |
      | https://www.teachit.co.uk/                                                           | true |
      | https://www.antibullying.net/                                                        | true |
      | https://www.microsoft.com/                                                           | true |
      | https://www.freefoto.com/                                                            | true |
      | https://www.comet.co.uk/                                                             | true |
      | https://www.youngminds.org.uk/                                                       | true |
      | https://www.northamptonshire.gov.uk/                                                 | true |
      | https://www.samlearning.co.uk/                                                       | true |
      | https://www.2g.myglobe.com.ph/main/wap/wml/category.do?id=1708/                      | true |
      | https://www.pendeford.org.uk/                                                        | true |
      | https://www.artres.com/                                                              | true |
      | https://www.ntlworld.com/                                                            | true |
      | https://www.planetdiary.com/                                                         | true |
      | https://www.literacytrust.org.uk/                                                    | true |
      | https://www.freejobsite.com/                                                         | true |
      | https://www.wolvescivic.co.uk/                                                       | true |
      | https://www.intuitivemedia.com/                                                      | true |
      | https://www.nicorette.co.uk/                                                         | true |
      | https://www.teach-ict.com/                                                           | true |
      | https://www.suite101.com/                                                            | true |
      | https://www.macromedia.com/                                                          | true |
      | https://www.wonderhowto.com/                                                         | true |
      | https://www.football365.com/                                                         | true |
      | https://www.artistdirect.com/                                                        | true |
      | https://www.recyclenow.com/                                                          | true |
      | https://www.topmarks.co.uk/                                                          | true |
      | https://www.timebank.org.uk/                                                         | true |
      | https://www.coppice-school.org.uk/                                                   | true |
      | https://www.onemission.com/entertainment/kids/                                       | true |
      | https://www.htc.com/                                                                 | true |
      | https://www.nspcc.org.uk/                                                            | true |
      | https://www.need2know.co.uk/                                                         | true |
      | https://www.noaa.gov/                                                                | true |
      | https://www.nhc.noaa.gov/                                                            | true |
      | https://www.asda.co.uk/                                                              | true |
      | https://www.barclays.mobi/                                                           | true |
      | https://www.gamed.ca/                                                                | true |
      | https://www.wolverhampton.gov.uk/                                                    | true |
      | https://www.accuweather.com/                                                         | true |
      | https://www.google.com/                                                              | true |
      | https://www.gifs.net/                                                                | true |
      | https://www.cadburyworld.co.uk/                                                      | true |
      | https://www.myglitterspace.com/                                                      | true |
      | https://www.brazil.com/                                                              | true |
      | https://www.chabad.org/                                                              | true |
      | https://www.fredleavitt.com/                                                         | true |
      | https://www.goldstarcafe.net/                                                        | true |
      | https://www.asos.com/                                                                | true |
      | https://www.roadsafetyni.gov.uk/                                                     | true |
      | https://www.jasa.net.au/                                                             | true |
      | https://www.janeausten.co.uk/                                                        | true |
      | https://www.constitutionparty.com/                                                   | true |
      | https://www.1000bananas.com/                                                         | true |
      | https://www.dell.com/                                                                | true |
      | https://www.pbs.org/                                                                 | true |
      | https://www.warnerbros.co.uk/                                                        | true |
      | https://www.edexcel.org.uk/                                                          | true |
      | https://www.safekids.com/                                                            | true |
      | https://www.smestow.org.uk/                                                          | true |
      | https://www.nhs.uk/                                                                  | true |
      | https://www.foxsports.com.au/                                                        | true |
      | https://www.yorku.ca/                                                                | true |
      | https://www.millenniumvolunteers.gov.uk/                                             | true |
      | https://www.wap.o2.co.uk/                                                            | true |
      | https://www.geographyatthemovies.co.uk/                                              | true |
      | https://www.aqa.org.uk/                                                              | true |
      | https://www.phonehouse.com/                                                          | true |
      | https://www.ocr.org.uk/                                                              | true |
      | https://www.en.beijing2008.cn/                                                       | true |
      | https://www.paypal.com/                                                              | true |
      | https://www.lovereading4schools.co.uk/                                               | true |
      | https://www.aqa.org/                                                                 | true |
      | https://www.smokefreeengland.co.uk/                                                  | true |
      | https://www.o2pocket.com/                                                            | true |
      | https://www.play.com/                                                                | true |
      | https://www.globalgateway.org.uk/                                                    | true |
      | https://www.answers.com/                                                             | true |
      | https://www.forbes.com/                                                              | true |
      | https://www.connexions-direct.com/                                                   | true |
      | https://www.ricojrguitars.com/                                                       | true |
      | https://www.bubbl.us/                                                                | true |
      | https://www.dorlingkindersley-uk.co.uk/                                              | true |
      | https://www.bookheads.org.uk/                                                        | true |
      | https://www.historychannel.co.uk/                                                    | true |
      | https://www.wikimedia.org/                                                           | true |
      | https://www.recycling-guide.org.uk/                                                  | true |
      | https://www.heathpark.net/                                                           | true |
      | https://www.yahoo.co.uk/                                                             | true |
      | https://www.chatdanger.com/                                                          | true |
      | https://www.whichfranchise.com/                                                      | true |
      | https://www.icaa.com/                                                                | true |
      | https://www.boltblue.com/                                                            | true |
      | https://www.carphonewarehouse.com/                                                   | true |
      | https://www.arkive.org/                                                              | true |
      | https://www.bized.co.uk/                                                             | true |
      | https://www.armyjobs.mod.uk/                                                         | true |
      | https://www.wolvcoll.ac.uk/                                                          | true |
      | https://www.instructables.com/                                                       | true |
      | https://www.o2.co.uk/                                                                | true |
      | https://www.met-office.gov.uk/                                                       | true |
      | https://www.kcroyals.com/                                                            | true |
      | https://www.readingmatters.co.uk/                                                    | true |
      | https://www.topshop.com/                                                             | true |
      | https://www.ypte.org.uk/                                                             | true |
      | https://www.surveymonkey.com/                                                        | true |
      | https://www.what2learn.com/                                                          | true |
      | https://www.tesco.com/                                                               | true |
      | https://www.amazon.co.uk/                                                            | true |
      | https://www.channel4.com/                                                            | true |
      | https://www.easymaths.com/                                                           | true |
      | https://www.bbc.co.uk/                                                               | true |
      | https://www.imdb.com/                                                                | true |
      | https://www.thesite.org/                                                             | true |
      | https://www.radio-locator.com/                                                       | true |
      | https://www.globaleducationderby.org.uk/                                             | true |
      | https://www.ferrariworld.com/                                                        | true |
      | https://www.headliners.org/                                                          | true |
      | https://www.businessstudiesonline.co.uk/                                             | true |
      | https://www.wednesfieldhigh.co.uk/                                                   | true |
      | https://www.wikipedia.org/                                                           | true |
      | https://www.logmein123.com/                                                          | true |
      | https://www.blue-print-studios.co.uk/                                                | true |
      | https://www.djbooth.net/                                                             | true |
      | https://www.wap.tesco-mobile.com/                                                    | true |
      | https://www.healthm8.net/                                                            | true |
      | https://www.expressandstar.com/                                                      | true |
      | https://www.freedigitalphotos.net/                                                   | true |
      | https://www.havenholidays.com/                                                       | true |
      | https://www.fonetastic.com/                                                          | true |
      | https://www.fast-autos.net/                                                          | true |
      | https://www.edmunds.biblio.net/                                                      | true |
      | https://www.rif.org.uk/                                                              | true |
      | https://www.thetimes100.co.uk/                                                       | true |
      | https://www.murderousmaths.co.uk/                                                    | true |
      | https://www.eathealthy.com/                                                          | true |
      | https://www.iconator.com/                                                            | true |
      | https://www.altontowers.com/                                                         | true |
      | https://www.lonelyplanet.com/                                                        | true |
      | https://www.talktofrank.com/                                                         | true |
      | https://www.ww1photos.com/                                                           | true |
      | https://www.learning2go.org/                                                         | true |
      | https://www.virginmedia.co.uk/                                                       | true |
      | https://www.live.com/                                                                | true |
      | https://www.radiotimes.com/                                                          | true |
      | https://www.pcworld.co.uk/                                                           | true |
      | https://www.ucas.com/                                                                | true |
      | https://www.en.wikipedia.org/                                                        | true |
      | https://www.samaritans.org/                                                          | true |
      | https://www.raspberry.forest.net/fmpro?-db=whootie.fp5&-lay=weblay&-format=/whootie/ | true |
      | https://www.135.196.23.137/pls/gn/v3_league.homepage?partner_id=109/                 | true |
      | https://www.mobile.bbc.co.uk/                                                        | true |
      | https://www.carbonneutral.com/                                                       | true |
      | https://www.google.co.uk/                                                            | true |
      | https://www.crystalgraphics.com/                                                     | true |
      | https://www.pemberley.com/                                                           | true |
      | https://www.gatm.org.uk/                                                             | true |
      | https://www.maps.google.co.uk/                                                       | true |
      | https://www.griefencounter.org.uk/                                                   | true |
      | https://www.mind-map.com/                                                            | true |
      | https://www.mobile.live.com/                                                         | true |
      | https://www.schoolresources.co.uk/                                                   | true |
      | https://www.scienceworld.wolfram.com/                                                | true |
      | https://www.thebrain.mcgill.ca/                                                      | true |
      | https://www.u-connect.me.uk/                                                         | true |
      | https://www.janeaustensoci.freeuk.com/                                               | true |
      | https://www.wolvcoll.blackboard.com/                                                 | true |
      | https://www.cia.gov/library/publications/the-world-factbook/                         | true |
      | https://www.bbc.co.uk/sport/                                                         | true |
      | https://www.safenetwork.org.uk/                                                      | true |
      | https://www.wolverhampton-engage.net/                                                | true |
      | https://www.my-iplan.com/                                                            | true |
      | https://www.codeclub.org.uk/                                                         | true |
      | https://www.weatheronline.co.uk/                                                     | true |
      | https://www.testurl.rulespace.com/o2pc/en/                                           | true |
      | https://www.nbc.com/                                                                 | true |
      | https://www.allfreecrafts.com/kids-crafts/                                           | true |
      | https://www.authorpoint.com/tabatha_jean_dagata/                                     | true |
      | https://www.commtechlab.msu.edu/                                                     | true |
      | https://www.datchet.com/users/rgordon/stmarysschool.htm/                             | true |
      | https://www.email.tesco-mobile.com/                                                  | true |
      | https://www.f.tesco-mobile.com/                                                      | true |
      | https://www.flbl.org/aboutus.php?phpsessid=73c63ed5915a31f9b2387aa2e29c3fd6/         | true |
      | https://www.free.tesco-mobile.com/                                                   | true |
      | https://www.go.motionbridge.com/                                                     | true |
      | https://www.indian-cultures.com/cultures/kayapo.html/                                | true |
      | https://www.indian-cultures.com/cultures/yanomamo.html/                              | true |
      | https://www.isa.wolvcoll.ac.uk/                                                      | true |
      | https://www.mobile.htc.com/                                                          | true |
      | https://www.o2.mxdata.co.uk/                                                         | true |
      | https://www.o2.mytrains.kizoom.co.uk/                                                | true |
      | https://www.o2active.ents24.com/                                                     | true |
      | https://www.o2chat.jumbuck.com/                                                      | true |
      | https://www.o2ukt.digitalrum.com/                                                    | true |
      | https://www.onemission.com/d.pl?dir=/entertainment/kids/                             | true |
      | https://www.periodic.lanl.gov/                                                       | true |
      | https://www.pine.cs.yale.edu/java/chess.html/                                        | true |
      | https://www.rt.tesco.volantis.net/                                                   | true |
      | https://www.story.lg.co.kr/english/                                                  | true |
      | https://www.teenzone.monster.co.uk/                                                  | true |
      | https://www.tesco.txt4content.com/                                                   | true |
      | https://www.tilburyhouse.com/childrens/                                              | true |
      | https://www.wap.o2.co.uk/myshortcuts/                                                | true |
      | https://www.wap.o2.co.uk/ndm/                                                        | true |
      | https://www.wap.o2.co.uk/parentalcontroltesco/                                       | true |
      | https://www.wap.o2.co.uk/pc/                                                         | true |
      | https://www.wap.o2.co.uk/thewhitelist/                                               | true |
      | https://www.wap.o2.co.uk/whitelistredirect/                                          | true |
      | https://www.wap.tescomobile.trust5.com/                                              | true |
      | https://www.wap.weatheronline.co.uk/                                                 | true |
      | https://www.wapmail.btinternet.com/                                                  | true |
      | https://www.wapmail.genie.co.uk/                                                     | true |
      | https://www.web.moreton.biblio.net/                                                  | true |
      | https://www.earthsky.com/kids/                                                       | true |
      | https://www.ee.ryerson.ca/~elf/abacus/                                               | true |
      | https://www.geography.learnontheinternet.co.uk/                                      | true |
      | https://www.highfields.wolverhampton.sch.uk/                                         | true |
      | https://www.phschool.com/science/planetdiary/                                        | true |
      | https://www.spartacus.schoolnet.co.uk/                                               | true |
      | https://www.uk.map24.com/                                                            | true |
      | https://www.bluebook.o2.co.uk/                                                       | true |
      | https://www.bsc.cards.go.com/crafts?page=craftdisplay&craftid=11082/                 | true |
      | https://www.cis.o2.co.uk/                                                            | true |
      | https://www.cis.ref.o2.co.uk/                                                        | true |
      | https://www.cis.ref.o2.co.uk/images/default/header_footer.png/                       | true |
      | https://www.cis.ref.o2.co.uk/pc/                                                     | true |
      | https://www.flash.o2.co.uk/                                                          | true |
      | https://www.mediamessaging.o2.co.uk/                                                 | true |
      | https://www.mmsc.mms.o2.co.uk/                                                       | true |
      | https://www.mobile.google.co.uk/                                                     | true |
      | https://www.mobile.microsoft.com/                                                    | true |
      | https://www.mywap.o2.co.uk/                                                          | true |
      | https://www.pdaimage.o2.co.uk/                                                       | true |
      | https://www.pdaimage.o2.co.uk/ndm/                                                   | true |
      | https://www.shakespeare.mit.edu/                                                     | true |
      | https://www.uk.weather.com/                                                          | true |
      | https://www.wap.ref.o2.co.uk/                                                        | true |
      | https://www.wap.ref.o2.co.uk/ndm/                                                    | true |
      | https://www.wap.ref.o2.co.uk/pc/                                                     | true |
      | https://www.wap.ref.o2.co.uk/thewhitelist/                                           | true |
      | https://www.wap.ref.o2.co.uk/whitelistredirect/                                      | true |
      | https://www.wap.sonyericsson.com/                                                    | true |
      | https://www.mobile.google.com/                                                       | true |
      | https://www.o2.iwap.kodakmobile.co.uk/                                               | true |
      | https://www.gherkinchallenge.org.uk/                                                 | true |
      | https://www.childline.org/                                                           | true |
      | https://www.citizenshipfoundation.org.uk/                                            | true |
      | https://www.capitalkidscricket.co.uk/                                                | true |
      | https://www.childline.co.uk/                                                         | true |
      | https://www.pacehealth.org.uk/                                                       | true |
      | https://www.youngstonewall.org.uk/                                                   | true |
      | https://www.lgbtyouth.org.uk/                                                        | true |
      | https://www.allsortsyouth.org.uk/                                                    | true |
      | https://www.llgs.org.uk/                                                             | true |
      | https://www.lgbtyouthnorthwest.org.uk/                                               | true |
      | https://www.lgbthistorymonth.org.uk/                                                 | true |
      | https://www.itgetsbetter.org/                                                        | true |
      | https://www.gaycenter.org/                                                           | true |
      | https://www.akt.org.uk/                                                              | true |
      | https://www.stonewall.org.uk/                                                        | true |
      | https://www.pinknews.co.uk/                                                          | true |
      | https://www.lgbt.co.uk/                                                              | true |
      | https://www.net-aware.org.uk/                                                        | true |
      | https://www.touch.whatsmyip.org/                                                     | true |
      | https://www.headers.formula4leadership.com/                                          | true |
      | https://www.noheaders.formula4leadership.com/                                        | true |
      | https://www.blackpoolbetterstart.org.uk/                                             | true |
      | https://www.copingwithcrying.org.uk/                                                 | true |
      | https://www.letterfromsanta.org.uk/                                                  | true |
      | https://www.nowiknow.org.uk/                                                         | true |
      | https://www.thecpsu.org.uk/                                                          | true |
      | https://www.childline.mobi/                                                          | true |
      | https://www.childline.net/                                                           | true |
