@nonmobile
Feature: Using Android Devices Check Top UK Sites and domains

  Scenario Outline: Using Android Browse top UK sites
    Given open chrome "<url>" and check http status "<bool>"

    Examples: 
      | url                                                    | bool  |
      | https://ichef.bbci.co.uk/                              | false |
      | https://www.mcdonalds.com/                             | false |
      | https://static.bbci.co.uk/                             | false |
      | https://www.arsenal.com/                               | false |
      | https://www.premierleague.com/                         | false |
      | https://lc-www-live-s.legocdn.com/                     | false |
      | https://resources.thefa.com/                           | false |
      | https://www.nottinghamforest.co.uk/                    | false |
      | https://www.irishfa.com/                               | false |
      | https://sh-s7-live-s.legocdn.com/                      | false |
      | https://cdn.thefa.com/                                 | false |
      | https://ticketingcontent.thefa.com/                    | false |
      | https://imagecomposer.nfl.com/                         | false |
      | https://www.lgfl.net/                                  | false |
      | https://www.visitsealife.com/                          | false |
      | https://lc-mediaplayerns-live-s.legocdn.com/           | false |
      | https://www.ecb.co.uk/                                 | false |
      | https://www.swfc.co.uk/                                | false |
      | https://www.watfordfc.com/                             | false |
      | https://www.bhasvic.ac.uk/                             | false |
      | https://www.chelseafc.com/                             | false |
      | https://www.lego.com/                                  | false |
      | https://book.disneylandparis.com/                      | false |
      | https://my.pottermore.com/                             | false |
      | https://www.whufc.com/                                 | false |
      | https://static-wildcat.nfl.com/                        | false |
      | https://www.rovers.co.uk/                              | false |
      | https://api.disney.com/                                | false |
      | https://wholegame.thefa.com/                           | false |
      | https://www.thedeep.co.uk/                             | false |
      | https://public-static.disneystorycentral.com/          | false |
      | https://www.abingdon.org.uk/                           | false |
      | https://www.zsl.org/                                   | false |
      | https://draft.premierleague.com/                       | false |
      | https://www.htafc.com/                                 | false |
      | https://brightcove.nascar.com/                         | false |
      | https://api.nfl.com/                                   | false |
      | https://store.asl.org/                                 | false |
      | https://pmdvod.nationalgeographic.com/                 | false |
      | https://frog.plume.essex.sch.uk/                       | false |
      | https://mail.colchester.ac.uk/                         | false |
      | https://media.rangers.co.uk/                           | false |
      | https://englandstore.thefa.com/                        | false |
      | https://services.universalorlando.com/                 | false |
      | https://mail.liverpoolfc.com/                          | false |
      | https://www.redimps.co.uk/                             | false |
      | https://www.nationalgalleries.org/                     | false |
      | https://ios.sc.api.fantasy.nfl.com/                    | false |
      | https://www.legoland.co.uk/                            | false |
      | https://www.cafc.co.uk/                                | false |
      | https://www.cpfc.co.uk/                                | false |
      | https://mi-od-live-s.legocdn.com/                      | false |
      | https://tickets.liverpoolfc.com/                       | false |
      | https://www.portsmouthfc.co.uk/                        | false |
      | https://www.wba.co.uk/                                 | false |
      | https://tickets.lcfc.com/                              | false |
      | https://tranmererovers.co.uk/                          | false |
      | https://www.sufc.co.uk/                                | false |
      | https://rangers.co.uk/                                 | false |
      | https://www.cumbria.ac.uk/                             | false |
      | https://www.dcfc.co.uk/                                | false |
      | https://www.lcfc.com/                                  | false |
      | https://www.mfc.co.uk/                                 | false |
      | https://helix.cumbria.ac.uk/                           | false |
      | https://prepvle.brightoncollege.net/                   | false |
      | https://www.itfc.co.uk/                                | false |
      | https://static.lgfl.net/                               | false |
      | https://www.thefa.com/                                 | false |
      | https://opm-dnx.disneylandparis.com/                   | false |
      | https://pma.premierleague.com/                         | false |
      | https://www.deanery.wigan.sch.uk/                      | false |
      | https://www.millwallfc.co.uk/                          | false |
      | https://www.kew.org/                                   | false |
      | https://tickets.scottishfa.co.uk/                      | false |
      | https://feeds.nfl.com/                                 | false |
      | https://fonts.arsenal.com/                             | false |
      | https://api.wdpro.disney.go.com/                       | false |
      | https://www.burnleyfootballclub.com/                   | false |
      | https://www.universalorlando.com/                      | false |
      | https://www.barnsleyfc.co.uk/                          | false |
      | https://happystudioassets.happymeal.com/               | false |
      | https://static.nfl.com/                                | false |
      | https://whippersnapperkids.com/                        | false |
      | https://firefly.sevenoaksschool.org/                   | false |
      | https://frog.kings.lincs.sch.uk/                       | false |
      | https://www.ntfc.co.uk/                                | false |
      | https://www.afcb.co.uk/                                | false |
      | https://www.canaries.co.uk/                            | false |
      | https://www.mkcollege.ac.uk/                           | false |
      | https://mountbatten.hants.sch.uk/                      | false |
      | https://firefly.clevedonschool.org.uk/                 | false |
      | https://www.skegness-aquarium.uk/                      | false |
      | https://www.nufc.co.uk/                                | false |
      | https://sales.disneylandparis.com/                     | false |
      | https://www.milkshake.tv/                              | false |
      | https://tickets.avfc.co.uk/                            | false |
      | https://portal1.chester.ac.uk/                         | false |
      | https://www.runshaw.ac.uk/                             | false |
      | https://www.bathrugby.com/                             | false |
      | https://videos.hasbro.com/                             | false |
      | https://www.bradfordcityfc.co.uk/                      | false |
      | https://wdpromedia.disney.go.com/                      | false |
      | https://www.shrewsburytown.com/                        | false |
      | https://seg.chelseafc.com/                             | false |
      | https://www.themillers.co.uk/                          | false |
      | https://images.pottermore.com/                         | false |
      | https://www.mkdons.com/                                | false |
      | https://cdn2.scratch.mit.edu/                          | false |
      | https://www.pzpn.pl/                                   | false |
      | https://eventspace.thefa.com/                          | false |
      | https://www.cheadlehulmeschool.co.uk/                  | false |
      | https://media-public.fcbarcelona.com/                  | false |
      | https://gateway.dorothy-stringer.co.uk/                | false |
      | https://www.coca-cola.co.uk/                           | false |
      | https://englandsupporters.thefa.com/                   | false |
      | https://www.nps.gov/                                   | false |
      | https://www.elfontheshelf.com/                         | false |
      | https://www.bletchleypark.org.uk/                      | false |
      | https://www.grange.org.uk/                             | false |
      | https://www.oldhamathletic.co.uk/                      | false |
      | https://www.bristolrovers.co.uk/                       | false |
      | https://www.qpr.co.uk/                                 | false |
      | https://webmail.eastbourne-college.co.uk/              | false |
      | https://tickets.evertonfc.com/                         | false |
      | https://www.readingfc.co.uk/                           | false |
      | https://www.hasbro.com/                                | false |
      | https://bletchleypark.org.uk/                          | false |
      | https://www.scunthorpe-united.co.uk/                   | false |
      | https://mailhost.lcfc.co.uk/                           | false |
      | https://services.mattel.com/                           | false |
      | https://www.bcfc.com/                                  | false |
      | https://www.afcwimbledon.co.uk/                        | false |
      | https://www.leytonorient.com/                          | false |
      | https://frog.ricardslodge.merton.sch.uk/               | false |
      | https://www.nottscountyfc.co.uk/                       | false |
      | https://frog.bournside.gloucs.sch.uk/                  | false |
      | https://www.colchester.ac.uk/                          | false |
      | https://www.life.org.uk/                               | false |
      | https://users.premierleague.com/                       | false |
      | https://cdn.tinypop.com/                               | false |
      | https://www.roalddahl.com/                             | false |
      | https://www.christs-hospital.org.uk/                   | false |
      | https://www.exetercityfc.co.uk/                        | false |
      | https://www.chesterfield.ac.uk/                        | false |
      | https://learningzone.delasalle.st-helens.sch.uk/       | false |
      | https://www.popfun.co.uk/                              | false |
      | https://www.rgs-guildford.co.uk/                       | false |
      | https://webmail2016.stpaulsschool.org.uk/              | false |
      | https://members.scouts.org.uk/                         | false |
      | https://station1.highcliffe.dorset.sch.uk/             | false |
      | https://www.sandcastle-waterpark.co.uk/                | false |
      | https://www.cardiffcityfc.co.uk/                       | false |
      | https://mail.qe.org/                                   | false |
      | https://shop.lcfc.com/                                 | false |
      | https://moas.thefa.com/                                | false |
      | https://mailbox.thefa.com/                             | false |
      | https://froglearn.backwellschool.net/                  | false |
      | https://bhasvle.bhasvic.ac.uk/                         | false |
      | https://www.southendunited.co.uk/                      | false |
      | https://ticketing.thefa.com/                           | false |
      | https://moodle.holycross.ac.uk/                        | false |
      | https://www.exe-coll.ac.uk/                            | false |
      | https://mail.alleyns.org.uk/                           | false |
      | https://theroyalschool.co.uk/                          | false |
      | https://www.weaverham.cheshire.sch.uk/                 | false |
      | https://owa.kings-ely.cambs.sch.uk/                    | false |
      | https://www2.visitsealife.com/                         | false |
      | https://webmail.hartpury.ac.uk/                        | false |
      | https://moodle.stgeorges.herts.sch.uk/                 | false |
      | https://mail.uphallprimary.co.uk/                      | false |
      | https://moodle.chester.ac.uk/                          | false |
      | https://www.alleyns.org.uk/                            | false |
      | https://www.pottermore.com/                            | false |
      | https://portal.chester.ac.uk/                          | false |
      | https://shsk.org.uk/                                   | false |
      | https://www.nascar.com/                                | false |
      | https://my-disneyland.disneylandparis.co.uk/           | false |
      | https://www.babytv.com/                                | false |
      | https://email.oundleschool.org.uk/                     | false |
      | https://assets.barbie.com/                             | false |
      | https://www.psg.fr/                                    | false |
      | https://estream.sherborne.org/                         | false |
      | https://www.pnefc.net/                                 | false |
      | https://www.burtonalbionfc.co.uk/                      | false |
      | https://theshed.chelseafc.com/                         | false |
      | https://teaching2and3yearolds.com/                     | false |
      | https://webmail.capitalcityacademy.org/                | false |
      | https://portal.spgs.org/                               | false |
      | https://mail.nhm.ac.uk/                                | false |
      | https://mail01.bryanston.co.uk/                        | false |
      | https://webmail.nationalgalleries.org/                 | false |
      | https://www.ccfc.co.uk/                                | false |
      | https://services.gallery.lego.com/                     | false |
      | https://webserver.forest.org.uk/                       | false |
      | https://forgirls.thefa.com/                            | false |
      | https://www.eureka.org.uk/                             | false |
      | https://www.theposh.com/                               | false |
      | https://news.marvel.com/                               | false |
      | https://mailhost.brightoncollege.net/                  | false |
      | https://reader.marvel.com/                             | false |
      | https://manchester.legolanddiscoverycentre.co.uk/      | false |
      | https://www.tinypop.com/                               | false |
      | https://www.portsmouth-college.ac.uk/                  | false |
      | https://parents.denstonecollege.org/                   | false |
      | https://mercury.stantonbury.org.uk/                    | false |
      | https://vle.flhs.wigan.sch.uk/                         | false |
      | https://www.purplemash.com/                            | false |
      | https://hero.highgateschool.org.uk/                    | false |
      | https://tickets.afc.co.uk/                             | false |
      | https://springfield.uk.net/                            | false |
      | https://webmail.strathallan.co.uk/                     | false |
      | https://www.saddlers.co.uk/                            | false |
      | https://www.opgs.org/                                  | false |
      | https://webmail.rfu.com/                               | false |
      | https://mobile.watfordfc.com/                          | false |
      | https://blackboard.uwe.ac.uk/                          | false |
      | https://ticketingpipeline.thefa.com/                   | false |
      | https://www.dundeeunitedfc.co.uk/                      | false |
      | https://www.nfl.com/                                   | false |
      | https://bookings.liverpoolfc.com/                      | false |
      | https://www.tibidabo.cat/                              | false |
      | https://www.scholastic.com/                            | false |
      | https://vle.brightoncollege.net/                       | false |
      | https://www.carlisleunited.co.uk/                      | false |
      | https://barclayschool.co.uk/                           | false |
      | https://learning.thefa.com/                            | false |
      | https://tickets.afcb.co.uk/                            | false |
      | https://www.bwfc.co.uk/                                | false |
      | https://saturn.jpl.nasa.gov/                           | false |
      | https://autodiscover.chester.ac.uk/                    | false |
      | https://firefly.kingschester.co.uk/                    | false |
      | https://www.wigan-leigh.ac.uk/                         | false |
      | https://www.barnetfc.com/                              | false |
      | https://www.redbridge-college.ac.uk/                   | false |
      | https://owa.uppingham.co.uk/                           | false |
      | https://www.truroschool.com/                           | false |
      | https://signin.lcfc.com/                               | false |
      | https://www.sevenoaksschool.org/                       | false |
      | https://parent.isams.rgs.newcastle.sch.uk/             | false |
      | https://lc-imageresizer-live-s.legocdn.com/            | false |
      | https://www.activityvillage.co.uk/                     | false |
      | https://premiumconcierge.arsenal.com/                  | false |
      | https://pass.chester.ac.uk/                            | false |
      | https://www.godolphinandlatymer.com/                   | false |
      | https://www.gillinghamfootballclub.com/                | false |
      | https://www.ashbridgeschool.co.uk/                     | false |
      | https://www.bella-bambinos.co.uk/                      | false |
      | https://outlook.chester.ac.uk/                         | false |
      | https://insight.coombegirlsschool.org/                 | false |
      | https://mail.swfc.co.uk/                               | false |
      | https://frog.stcolumbascollege.org/                    | false |
      | https://parents.lehs.org.uk/                           | false |
      | https://media.mattel.com/                              | false |
      | https://vle.northchaddertonschool.co.uk/               | false |
      | https://sad.hasbro.com/                                | false |
      | https://www.icc-cricket.com/                           | false |
      | https://shop.chesterzoo.org/                           | false |
      | https://mail.mcsoxford.org/                            | false |
      | https://realtime-content-propagation.wdpro.disney.com/ | false |
      | https://fulltime-admin.thefa.com/                      | false |
      | https://www.sherborne.org/                             | false |
      | https://palmaaquarium.com/                             | false |
      | https://www.paigntonzoo.org.uk/                        | false |
      | https://learning.alleyns.org.uk/                       | false |
      | https://mylearning.cumbria.ac.uk/                      | false |
      | https://www.crewealex.net/                             | false |
      | https://uploads.scratch.mit.edu/                       | false |
      | https://ohmy.disney.com/                               | false |
      | https://moodle.srv.hull-college.ac.uk/                 | false |
      | https://www.biltongrange.co.uk/                        | false |
      | https://www.glenthorne.sutton.sch.uk/                  | false |
      | https://brochure.disneylandparis.com/                  | false |
      | https://www.avfc.co.uk/                                | false |
      | https://www.elmleynaturereserve.co.uk/                 | false |
      | https://coyg.arsenal.com/                              | false |
      | https://www.swindontownfc.co.uk/                       | false |
      | https://frog.thamesmead.surrey.sch.uk/                 | false |
      | https://www.haribo.com/                                | false |
      | https://main.isams.rgs.newcastle.sch.uk/               | false |
      | https://www.raynespark.merton.sch.uk/                  | false |
      | https://www.crawleytownfc.com/                         | false |
      | https://mail.cpfc.co.uk/                               | false |
      | https://bsp.bradfieldcollege.org.uk/                   | false |
      | https://www1.chester.ac.uk/                            | false |
      | https://cneos.jpl.nasa.gov/                            | false |
      | https://www.warnerbros.com/                            | false |
      | https://voyager.jpl.nasa.gov/                          | false |
      | https://www.doncasterroversfc.co.uk/                   | false |
      | https://www.chesterfield-fc.co.uk/                     | false |
      | https://www.habsgirls.org.uk/                          | false |
      | https://ak-static.cms.nba.com/                         | false |
      | https://www.esherrugby.com/                            | false |
      | https://www.qeliz.ac.uk/                               | false |
      | https://portal.exe-coll.ac.uk/                         | false |
      | https://portal.winstanley.ac.uk/                       | false |
      | https://maggieandrose.com/                             | false |
      | https://www.stevenagefc.com/                           | false |
      | https://mail.blundells.org/                            | false |
      | https://www.pgrfc.co.uk/                               | false |
      | https://mail.ellesmere.leicester.sch.uk/               | false |
      | https://tickets.quins.co.uk/                           | false |
      | https://mail.newcastle-falcons.co.uk/                  | false |
      | https://tickets.canaries.co.uk/                        | false |
      | https://store.saintsfc.co.uk/                          | false |
      | https://www.theshots.co.uk/                            | false |
      | https://static.mymaths.co.uk/                          | false |
      | https://www.torquayunited.com/                         | false |
      | https://ideas.lego.com/                                | false |
      | https://www.port-vale.co.uk/                           | false |
      | https://connect.rainford.org.uk/                       | false |
      | https://www.palmers.ac.uk/                             | false |
      | https://bookings.arsenal.com/                          | false |
      | https://mail.oundleschool.org.uk/                      | false |
      | https://www.qebarnet.co.uk/                            | false |
      | https://www.oufc.co.uk/                                | false |
      | https://intranet.latymer-upper.org/                    | false |
      | https://www.royalballetschool.org.uk/                  | false |
      | https://parents.headington.org/                        | false |
      | https://mail.adbm.britishmuseum.org/                   | false |
      | https://www.stanway-pri.essex.sch.uk/                  | false |
      | https://shop.quins.co.uk/                              | false |
      | https://tickets.dcfc.co.uk/                            | false |
      | https://webmail.mkdons.com/                            | false |
      | https://md2.thefa.com/                                 | false |
      | https://www.thecollege.co.uk/                          | false |
      | https://sandringham.herts.sch.uk/                      | false |
      | https://www.stpaulsacademy.org.uk/                     | false |
      | https://static.kano.me/                                | false |
      | https://portal.fettes.com/                             | false |
      | https://intranet.stpaulsschool.org.uk/                 | false |
      | https://artsed.co.uk/                                  | false |
      | https://www.stchris.co.uk/                             | false |
      | https://vle.budehaven.cornwall.sch.uk/                 | false |
      | https://tickets.palmaaquarium.com/                     | false |
      | https://www.cityplym.ac.uk/                            | false |
      | https://webmail.burycollege.ac.uk/                     | false |
      | https://insight.saintgeorgescofe.kent.sch.uk/          | false |
      | https://www.ytfc.net/                                  | false |
      | https://www.bcfc.co.uk/                                | false |
      | https://www.walbottlecampus.newcastle.sch.uk/          | false |
      | https://mail.perse.co.uk/                              | false |
      | https://tickets.saintsfc.co.uk/                        | false |
      | https://www.perse.co.uk/                               | false |
      | https://mail.lpgs.bromley.sch.uk/                      | false |
      | https://www.walsallacademy.com/                        | false |
      | https://superstore.afcb.co.uk/                         | false |
      | https://nationalzoo.si.edu/                            | false |
      | https://mydisneyphotopass.disney.go.com/               | false |
      | https://eas.peterborough.ac.uk/                        | false |
      | https://www.eastridingcollege.ac.uk/                   | false |
      | https://portal.stswithuns.com/                         | false |
      | https://www.space.com/                                 | false |
      | https://cdn.celticfc.net/                              | false |
      | https://www.jkrowling.com/                             | false |
      | https://gateway.blenheim.surrey.sch.uk/                | false |
      | https://mail.greatsankey.org/                          | false |
      | https://read-api.marvel.com/                           | false |
      | https://www.booktickets.disneylandparis.com/           | false |
      | https://gms.rfu.com/                                   | false |
      | https://vle.hillview.kent.sch.uk/                      | false |
      | https://public.droitwichspahigh.worcs.sch.uk/          | false |
      | https://www.preston.ac.uk/                             | false |
      | https://www.brock.ac.uk/                               | false |
      | https://junior.warwickschool.org/                      | false |
      | https://events.popjam.com/                             | false |
      | https://www.whitehouse.gov/                            | false |
      | https://smetrics.nfl.com/                              | false |
      | https://www.deepseaworld.com/                          | false |
      | https://voices.nationalgeographic.org/                 | false |
      | https://marvle.marling.gloucs.sch.uk/                  | false |
      | https://cdn.assets.scratch.mit.edu/                    | false |
      | https://clubshop.cafc.co.uk/                           | false |
      | https://ajslearning.alleyns.org.uk/                    | false |
      | https://myws.uwe.ac.uk/                                | false |
      | https://mail.bridgeacademy.hackney.sch.uk/             | false |
      | https://billetterie.psg.fr/                            | false |
      | https://mail.winstanley.ac.uk/                         | false |
      | https://mail.chesterzoo.org/                           | false |
      | https://vle.kings-school.co.uk/                        | false |
      | https://store.stokecityfc.com/                         | false |
      | https://bedalesvle.bedales.org.uk/                     | false |
      | https://www.leedsunited.com/                           | false |
      | https://api.afl.com.au/                                | false |
      | https://www.plumpton.ac.uk/                            | false |
      | https://www.northamptonsaints.co.uk/                   | false |
      | https://portal.st-bedes.surrey.sch.uk/                 | false |
      | https://gateway.chigwell-school.org/                   | false |
      | https://tickets.nufc.co.uk/                            | false |
      | https://elearning.ecb.co.uk/                           | false |
      | https://api.marvel.com/                                | false |
      | https://www.blackpoolfc.co.uk/                         | false |
      | https://www.beths.bexley.sch.uk/                       | false |
      | https://sipr-evision.chester.ac.uk/                    | false |
      | https://portal.cranbrook.kent.sch.uk/                  | false |
      | https://stillmed.olympic.org/                          | false |
      | https://webmail.zsl.org/                               | false |
      | https://firefly.bradfieldcollege.org.uk/               | false |
      | https://www.rutlish.merton.sch.uk/                     | false |
      | https://www.stonyhurst.ac.uk/                          | false |
      | https://pupilp.epsomcollege.org.uk/                    | false |
      | https://www.cu-fc.com/                                 | false |
      | https://parents.reigategrammar.org/                    | false |
      | https://kidsactivitiesblog.com/                        | false |
      | https://www.chhs.stockport.sch.uk/                     | false |
      | https://frog.greenshaw.co.uk/                          | false |
      | https://insight.richmondschool.net/                    | false |
      | https://www.crusadersfc.com/                           | false |
      | https://www.zoo-berlin.de/                             | false |
      | https://i.theleys.net/                                 | false |
      | https://countymail.thefa.com/                          | false |
      | https://vle.bennett.kent.sch.uk/                       | false |
      | https://www.ccs.northants.sch.uk/                      | false |
      | https://primary.southbank.org/                         | false |
      | https://mcdonalds.com.au/                              | false |
      | https://www.mcsoxford.org/                             | false |
      | https://msx-cas.uppingham.co.uk/                       | false |
      | https://www.girlguiding-anglia.org.uk/                 | false |
      | https://webmail.sandwellacademy.com/                   | false |
      | https://rewards.avfc.co.uk/                            | false |
      | https://vle.hilbre.wirral.sch.uk/                      | false |
      | https://www.gwc.org.uk/                                | false |
      | https://tickets.nottinghamforest.co.uk/                | false |
      | https://www.qmc.ac.uk/                                 | false |
      | https://feeds.sherborne.org/                           | false |
      | https://mail.kingsbruton.com/                          | false |
      | https://apps.chester.ac.uk/                            | false |
      | https://www.wrexhamafc.co.uk/                          | false |
      | https://www.wbkidsgo.com/                              | false |
      | https://www.budmouth.dorset.sch.uk/                    | false |
      | https://www.st-joanofarc.islington.sch.uk/             | false |
      | https://www.thinkuknow.co.uk/                          | false |
      | https://mail.robert-clack.bardaglea.org.uk/            | false |
      | https://www.bca.ac.uk/                                 | false |
      | https://fivesisterszoo.co.uk/                          | false |
      | https://owa.rfu.com/                                   | false |
      | https://moodle.rave.ac.uk/                             | false |
      | https://webmail.lehs.org.uk/                           | false |
      | https://www.stockton.ac.uk/                            | false |
      | https://lv-nexoknights-live-s.legocdn.com/             | false |
      | https://www.liverpoolfc.com/                           | false |
      | https://uppnet2.uppingham.co.uk/                       | false |
      | https://www.imax.com/                                  | false |
      | https://www.sixflags.com/                              | false |
      | https://www.thunderbirds.com/                          | false |
      | https://www.newbury-college.ac.uk/                     | false |
      | https://cdn1.educationcity.com/                        | false |
      | https://blog.life.org.uk/                              | false |
      | https://www.nhl.com/                                   | false |
      | https://www.asl.org/                                   | false |
      | https://parents.trentcollege.net/                      | false |
      | https://vle.swgs.wilts.sch.uk/                         | false |
      | https://moodle.lodeheath.org.uk/                       | false |
      | https://exchange.invicta.kent.sch.uk/                  | false |
      | https://top-childcare.co.uk/                           | false |
      | https://portal.droitwichspahigh.worcs.sch.uk/          | false |
      | https://webmail.sfx.ac.uk/                             | false |
      | https://booking.edenproject.com/                       | false |
      | https://film-assets.ushmm.org/                         | false |
      | https://www.wickersley.net/                            | false |
      | https://mail.canford.com/                              | false |
      | https://wwwsecure.lego.com/                            | false |
      | https://vle.nobel.herts.sch.uk/                        | false |
      | https://mail.colne.essex.sch.uk/                       | false |
      | https://owa.ardingly.com/                              | false |
      | https://service.mattel.com/                            | false |
      | https://exchange.coxgreen.com/                         | false |
      | https://w3.chabad.org/                                 | false |
      | https://w5.chabad.org/                                 | false |
      | https://frog.bedford.wigan.sch.uk/                     | false |
      | https://kidsongs.com/                                  | false |
      | https://webmail.george-spencer.notts.sch.uk/           | false |
      | https://gateway.marvel.com/                            | false |
      | https://www.mymaths.co.uk/                             | false |
      | https://www.lehs.org.uk/                               | false |
      | https://shop.afcwimbledon.co.uk/                       | false |
      | https://static.sixflags.com/                           | false |
      | https://webmail.theleys.net/                           | false |
      | https://mail.camre.ac.uk/                              | false |
      | https://www.scarboroughcollege.co.uk/                  | false |
      | https://www.ushmm.org/                                 | false |
      | https://mobile.kimbolton.cambs.sch.uk/                 | false |
      | https://uk.rubiks.com/                                 | false |
      | https://webmail.george-heriots.com/                    | false |
      | https://extranet.holycross.ac.uk/                      | false |
      | https://citrix.thefa.com/                              | false |
      | https://www.wildern.hants.sch.uk/                      | false |
      | https://pupils.stpaulsschool.org.uk/                   | false |
      | https://www.bedfordschool.org.uk/                      | false |
      | https://shop.universalorlando.com/                     | false |
      | https://www.chosen-hill.gloucs.sch.uk/                 | false |
      | https://stanborough.herts.sch.uk/                      | false |
      | https://www.ka-net.org.uk/                             | false |
      | https://arcpow.uwe.ac.uk/                              | false |
      | https://lc-avatarimage-live-s.legocdn.com/             | false |
      | https://moodle.longdean.herts.sch.uk/                  | false |
      | https://isams.canford.com/                             | false |
      | https://mail.furness.ac.uk/                            | false |
      | https://mail.dovercollege.org.uk/                      | false |
      | https://mail.northamptonsaints.co.uk/                  | false |
      | https://welcome.uwe.ac.uk/                             | false |
      | https://insight.plumsteadmanor.com/                    | false |
      | https://www.sheffieldhighschool.org.uk/                | false |
      | https://www.hummersknott.org.uk/                       | false |
      | https://www.thamesmead.surrey.sch.uk/                  | false |
      | https://mail.merchiston.co.uk/                         | false |
      | https://blog.universalorlando.com/                     | false |
      | https://webmail.horndeantc.hants.sch.uk/               | false |
      | https://student.isams.rgs.newcastle.sch.uk/            | false |
      | https://insight.magdalen.northants.sch.uk/             | false |
      | https://extranet.qpcs.brent.sch.uk/                    | false |
      | https://www.southamcollege.com/                        | false |
      | https://extranet.christs-hospital.org.uk/              | false |
      | https://www.frederickgoughschool.co.uk/                | false |
      | https://www.usj.co.jp/                                 | false |
      | https://www.spavalleyrailway.co.uk/                    | false |
      | https://portal.nortonhillschool.com/                   | false |
      | https://m.alsa.es/                                     | false |
      | https://insight.malbank.cheshire.sch.uk/               | false |
      | https://m.drusillas.co.uk/                             | false |
      | https://taronga.org.au/                                | false |
      | https://mail.kingswood.bath.sch.uk/                    | false |
      | https://webmail.sussexdowns.ac.uk/                     | false |
      | https://exchange.tauntonschool.co.uk/                  | false |
      | https://websales.safc.com/                             | false |
      | https://cedar.osfc.ac.uk/                              | false |
      | https://owa.poolegrammar.com/                          | false |
      | https://media-static.fcbarcelona.com/                  | false |
      | https://information.ccs.northants.sch.uk/              | false |
      | https://www.drusillas.co.uk/                           | false |
      | https://mailroom.nelson.ac.uk/                         | false |
      | https://www.northbridgehouse.com/                      | false |
      | https://www.spellingcity.com/                          | false |
      | https://email.kshsonline.com/                          | false |
      | https://images.nufc.co.uk/                             | false |
      | https://www.stanfordjun.brighton-hove.sch.uk/          | false |
      | https://www.wagggs.org/                                | false |
      | https://www.educationcity.com/                         | false |
      | https://remote.barnsleyfc.co.uk/                       | false |
      | https://www.windlesham.com/                            | false |
      | https://www.archives.gov/                              | false |
      | https://nerf.hasbro.com/                               | false |
      | https://moodle.yateley.hants.sch.uk/                   | false |
      | https://my.cumbria.ac.uk/                              | false |
      | https://store.juventus.com/                            | false |
      | https://exchange.loreto.ac.uk/                         | false |
      | https://mail.jameshornsby.essex.sch.uk/                | false |
      | https://www.parcasterix.fr/                            | false |
      | https://mylittlepony.hasbro.com/                       | false |
      | https://server2.parliamenthill.camden.sch.uk/          | false |
      | https://www.beano.com/                                 | false |
      | https://cdn.scratch.mit.edu/                           | false |
      | https://mail.hovepark.org.uk/                          | false |
      | https://mail.ribstonhall.gloucs.sch.uk/                | false |
      | https://webmail.macclesfield.ac.uk/                    | false |
      | https://search2.lego.com/                              | false |
      | https://portal.oundleschool.org.uk/                    | false |
      | https://portal.gdst.net/                               | false |
      | https://shop.zsl.org/                                  | false |
      | https://www.theglasgowacademy.org.uk/                  | false |
      | https://mailserver.st-peters.york.sch.uk/              | false |
      | https://firefly.horndeantc.hants.sch.uk/               | false |
      | https://outlook.celticfc.co.uk/                        | false |
      | https://www.weymouth.ac.uk/                            | false |
      | https://mail.paigntonzoo.org.uk/                       | false |
      | https://store.psg.fr/                                  | false |
      | https://www.edenproject.com/                           | false |
      | https://mail.bartoncourt.org/                          | false |
      | https://www.aquariumbcn.com/                           | false |
      | https://www.jpl.nasa.gov/                              | false |
      | https://go.s.coke.com/                                 | false |
      | https://www.dragonschool.org/                          | false |
      | https://www.lrgs.org.uk/                               | false |
      | https://en.psg.fr/                                     | false |
      | https://www.balearia.com/                              | false |
      | https://www.drfc.co.uk/                                | false |
      | https://mail.sgschool.org.uk/                          | false |
      | https://remoteaccess.imberhorne.w-sussex.sch.uk/       | false |
      | https://mail.oldhamathletic.co.uk/                     | false |
      | https://www.fcbarcelona.com/                           | false |
      | https://eh-mail01.esherhigh.surrey.sch.uk/             | false |
      | https://webmail.davinci.derby.sch.uk/                  | false |
      | https://webmail.colstons.bristol.sch.uk/               | false |
      | https://www.butehouse.co.uk/                           | false |
      | https://player.arsenal.com/                            | false |
      | https://www.ctfc.com/                                  | false |
      | https://www.strathallan.co.uk/                         | false |
      | https://booking.cafc.co.uk/                            | false |
      | https://www.forest.org.uk/                             | false |
      | https://email.golbornehigh.wigan.sch.uk/               | false |
      | https://www.tormeadschool.org.uk/                      | false |
      | https://portal.allhallows.org.uk/                      | false |
      | https://www.highgateschool.org.uk/                     | false |
      | https://webmail.bcfc.co.uk/                            | false |
      | https://mail.st-thomasmore.southend.sch.uk/            | false |
      | https://www.cleveland.ac.uk/                           | false |
      | https://scbraga.pt/                                    | false |
      | https://www.shsk.org.uk/                               | false |
      | https://shop.afc.co.uk/                                | false |
      | https://hls.brainpop.com/                              | false |
      | https://mail.hawthorns.com/                            | false |
      | https://volga13.notredame-high.co.uk/                  | false |
      | https://webmail.kingswood.bath.sch.uk/                 | false |
      | https://webmail.weydonschool.surrey.sch.uk/            | false |
      | https://www.arnewood.hants.sch.uk/                     | false |
      | https://whs.wolstanton.staffs.sch.uk/                  | false |
      | https://images.mattel.com/                             | false |
      | https://mail.deepingschool.org.uk/                     | false |
      | https://remote.ousedale.org.uk/                        | false |
      | https://www.kes.hants.sch.uk/                          | false |
      | https://shc-exch01.shootershill.ac.uk/                 | false |
      | https://mail.dragonschool.org/                         | false |
      | https://www.princethorpe.co.uk/                        | false |
      | https://scratch.mit.edu/                               | false |
      | https://www.burford.oxon.sch.uk/                       | false |
      | https://exe-coll.ac.uk/                                | false |
      | https://byod.sherborne.org/                            | false |
      | https://webaccess.canaries.co.uk/                      | false |
      | https://lfcem09.liverpoolfc.com/                       | false |
      | https://studentadvantage.bhasvic.ac.uk/                | false |
      | https://portal2.billericay.essex.sch.uk/               | false |
      | https://mailserver.st-columbas.org/                    | false |
      | https://insight.cotswold.gloucs.sch.uk/                | false |
      | https://wa.disneylandparis.com/                        | false |
      | https://svglive3-event.level3.nfl.com/                 | false |
      | https://www.mathsisfun.com/                            | false |
      | https://eas.ttsonline.net/                             | false |
      | https://www.legoland.com/                              | false |
      | https://insight.forest.wokingham.sch.uk/               | false |
      | https://idp.uwe.ac.uk/                                 | false |
      | https://parents.invicta.kent.sch.uk/                   | false |
      | https://mail.shiplake.org.uk/                          | false |
      | https://email.eltham-college.org.uk/                   | false |
      | https://exchange.qe.dorset.sch.uk/                     | false |
      | https://www.barnardcastleschool.org.uk/                | false |
      | https://moat.leicester.sch.uk/                         | false |
      | https://www.loc.gov/                                   | false |
      | https://da.wolfsonhillel.enfield.sch.uk/               | false |
      | https://cliftonvillefc.net/                            | false |
      | https://www.bayhouse.hants.sch.uk/                     | false |
      | https://mail.cranbourne.hants.sch.uk/                  | false |
      | https://www.disneylandparis.com/                       | false |
      | https://www.bristolrugby.co.uk/                        | false |
      | https://portal.polar-tep.eo.esa.int/                   | false |
      | https://insight.chewvalleyschool.co.uk/                | false |
      | https://www.buckswood.co.uk/                           | false |
      | https://mysearch.quins.co.uk/                          | false |
      | https://mobile.grange.org.uk/                          | false |
      | https://www.badmintonschool.co.uk/                     | false |
      | https://w4.chabad.org/                                 | false |
      | https://www.jacquelinewilson.co.uk/                    | false |
      | https://www.livingcoasts.org.uk/                       | false |
      | https://bacoll.ac.uk/                                  | false |
      | https://vle.chase.worcs.sch.uk/                        | false |
      | https://webmail.cranbrook.kent.sch.uk/                 | false |
      | https://www.natgeokids.com/                            | false |
      | https://tasc.thamesmead.surrey.sch.uk/                 | false |
      | https://webmail.sherborne.org/                         | false |
      | https://www.wolves.co.uk/                              | false |
      | https://frog.cranford.hounslow.sch.uk/                 | false |
      | https://frog.wiseman.ealing.sch.uk/                    | false |
      | https://mail.saintolaves.net/                          | false |
      | https://learning.kesbath.com/                          | false |
      | https://www.st-mary.blackpool.sch.uk/                  | false |
      | https://cdn.thisissand.com/                            | false |
      | https://mail.palmers.ac.uk/                            | false |
      | https://api.kidscrape.com/                             | false |
      | https://facoachstore.thefa.com/                        | false |
      | https://www.warwickschool.org/                         | false |
      | https://www.notredame-high.co.uk/                      | false |
      | https://webmail.amersham.ac.uk/                        | false |
      | https://studentportal.burycollege.ac.uk/               | false |
      | https://firefly.valentines-sch.org.uk/                 | false |
      | https://www.stjamesschools.co.uk/                      | false |
      | https://owa.eastwood.southend.sch.uk/                  | false |
      | https://www.acmilan.com/                               | false |
      | https://compass.scouts.org.uk/                         | false |
      | https://mail.artsed.co.uk/                             | false |
      | https://owa.birkdaleschool.org.uk/                     | false |
      | https://www.eastberks.ac.uk/                           | false |
      | https://www.crompton.oldham.sch.uk/                    | false |
      | https://www.ahs.me.uk/                                 | false |
      | https://mail.pursglove.ac.uk/                          | false |
      | https://www.akeleywoodschool.co.uk/                    | false |
      | https://www.george-heriots.com/                        | false |
      | https://statsapi.web.nhl.com/                          | false |
      | https://www.knex.com/                                  | false |
      | https://www.totton.ac.uk/                              | false |
      | https://nrich.maths.org/                               | false |
      | https://mail.kingschester.co.uk/                       | false |
      | https://alumni.latymer-upper.org/                      | false |
      | https://www.abblanch.com/                              | false |
      | https://www.hertsleague.co.uk/                         | false |
      | https://pupilportal.queenswood.org/                    | false |
      | https://www.grahamschool.co.uk/                        | false |
      | https://mail.sjd.ac.uk/                                | false |
      | https://remote.crawleytownfc.com/                      | false |
      | https://exchange.qehbristol.co.uk/                     | false |
      | https://oscar.eltham-college.org.uk/                   | false |
      | https://ssc.shakhtar.com/                              | false |
      | https://webaccess.nufc.co.uk/                          | false |
      | https://secure.disney.com/                             | false |
      | https://discoveringegypt.com/                          | false |
      | https://webmail.glenthorne.sutton.sch.uk/              | false |
      | https://webmail.evertonfc.com/                         | false |
      | https://moodle2.wyedean.gloucs.sch.uk/                 | false |
      | https://mail.holloway.islington.sch.uk/                | false |
      | https://www.teachyourmonstertoread.com/                | false |
      | https://marsmobile.jpl.nasa.gov/                       | false |
      | https://mail.leedsunited.com/                          | false |
      | https://tickets.fcbarcelona.com/                       | false |
      | https://mail.preston.ac.uk/                            | false |
      | https://www.archbishopholgates.org/                    | false |
      | https://isams-pupils.lrgs.org.uk/                      | false |
      | https://www.oakmanor.brent.sch.uk/                     | false |
      | https://mail.tigers.co.uk/                             | false |
      | https://mdp-media.acmilan.com/                         | false |
      | https://theblues.chelseafc.com/                        | false |
      | https://mail.philipmorant.essex.sch.uk/                | false |
      | https://hbk-exchange.hayesbrook.kent.sch.uk/           | false |
      | https://analytics.disneyinternational.com/             | false |
      | https://webmail.eatonsquareschool.com/                 | false |
      | https://directaccess.rfu.com/                          | false |
      | https://schoolpost.chigwell-school.org/                | false |
      | https://klbschool.org.uk/                              | false |
      | https://mail.kesgrave.suffolk.sch.uk/                  | false |
      | https://appconfig.svc.nhl.com/                         | false |
      | https://folders.harveygs.kent.sch.uk/                  | false |
      | https://stillres.olympic.org/                          | false |
      | https://ninjagochallenge.lego.com/                     | false |
      | https://frog.judd.kent.sch.uk/                         | false |
      | https://www.stbrn.ac.uk/                               | false |
      | https://west.cdn.mathletics.com/                       | false |
      | https://gateway.stpaulscatholiccollege.co.uk/          | false |
      | https://mail.folkestoneacademy.com/                    | false |
      | https://internal.sellyoak.bham.sch.uk/                 | false |
      | https://www.rom.on.ca/                                 | false |
      | https://portal.ridgewayschool.com/                     | false |
      | https://webmail.lampton.hounslow.sch.uk/               | false |
      | https://webmail.dsfc.ac.uk/                            | false |
      | https://media.nationalgeographic.org/                  | false |
      | https://www.trurohigh.co.uk/                           | false |
      | https://ext.whitegrove.bracknell-forest.sch.uk/        | false |
      | https://mail.cafc.co.uk/                               | false |
      | https://bishopscannings.wilts.sch.uk/                  | false |
      | https://exchange.hlc.org.uk/                           | false |
      | https://mail.bsfc.ac.uk/                               | false |
      | https://mailserver.royalmasonic.herts.sch.uk/          | false |
      | https://mail.highworth.kent.sch.uk/                    | false |
      | https://mail.bishopveseys.bham.sch.uk/                 | false |
      | https://moodle.chaucer.sheffield.sch.uk/               | false |
      | https://parents.eaglehouseschool.com/                  | false |
      | https://intranet.kes.hants.sch.uk/                     | false |
      | https://vle.bethanyschool.org.uk/                      | false |
      | https://vle.heatonmanor.newcastle.sch.uk/              | false |
      | https://mail.tarporleyhigh.co.uk/                      | false |
      | https://obclub.bedfordschool.org.uk/                   | false |
      | https://www.crackerbarrel.com/                         | false |
      | https://www.chester.ac.uk/                             | false |
      | https://www.alsa.es/                                   | false |
      | https://emoji.kelloggs.com/                            | false |
      | https://owa.westhillpark.com/                          | false |
      | https://moodle2.ssfc.ac.uk/                            | false |
      | https://api.curiosity.com/                             | false |
      | https://webmail.launceston-college.cornwall.sch.uk/    | false |
      | https://mail.sheldonschool.co.uk/                      | false |
      | https://www.dehortus.nl/                               | false |
      | https://www.eastleigh.ac.uk/                           | false |
      | https://mail.hummersknott.org.uk/                      | false |
      | https://email.ea.e-renfrew.sch.uk/                     | false |
      | https://frog.ksn.org.uk/                               | false |
      | https://owa.reigategrammar.org/                        | false |
      | https://static.abcteach.com/                           | false |
      | https://hsw.co.uk/                                     | false |
      | https://cedar.stmarysblackburn.ac.uk/                  | false |
      | https://moodle.stanborough.herts.sch.uk/               | false |
      | https://www.sportsandleisure.abingdon.org.uk/          | false |
      | https://auth.evertonfc.com/                            | false |
      | https://my.catscollege.com/                            | false |
      | https://www.hillview.kent.sch.uk/                      | false |
      | https://mail.aldenham.com/                             | false |
      | https://mail.chelseafc.com/                            | false |
      | https://www.americangirl.com/                          | false |
      | https://www.klbschool.org.uk/                          | false |
      | https://www.bramhallhigh.stockport.sch.uk/             | false |
      | https://www.colchsfc.ac.uk/                            | false |
      | https://www.pairidaiza.eu/                             | false |
      | https://fettes.com/                                    | false |
      | https://mail.bedford.ac.uk/                            | false |
      | https://stpaulscatholiccollege.co.uk/                  | false |
      | https://www.mhschool.com/                              | false |
      | https://www.mrmen.com/                                 | false |
      | https://webmail.stockportgrammar.co.uk/                | false |
      | https://mail.rooksheath.harrow.sch.uk/                 | false |
      | https://hamptonschool.org.uk/                          | false |
      | https://mail.heathfieldcc.e-sussex.sch.uk/             | false |
      | https://ilearn.sussexdowns.ac.uk/                      | false |
      | https://mail.stedmundscollege.org/                     | false |
      | https://www.queenelizabeths.derbyshire.sch.uk/         | false |
      | https://newmail.stockport.ac.uk/                       | false |
      | https://grove.wilts.sch.uk/                            | false |
      | https://mail.riverstonschool.co.uk/                    | false |
      | https://gigya.arsenal.com/                             | false |
      | https://mis.surbitonhigh.com/                          | false |
      | https://www.dierenparkamersfoort.nl/                   | false |
      | https://pupils.farnborough-hill.org.uk/                | false |
      | https://www.dfb.de/                                    | false |
      | https://www.bicton.ac.uk/                              | false |
      | https://tickets.aqualandia.net/                        | false |
      | https://www.mail.stvincent.ac.uk/                      | false |
      | https://intranet.rgs-guildford.co.uk/                  | false |
      | https://interactive.sesameonline.net/                  | false |
      | https://vle.monkwearmouth.sunderland.sch.uk/           | false |
      | https://intranet.royalhospitalschool.org/              | false |
      | https://gateway.canford.com/                           | false |
      | https://exchange.eastleigh.ac.uk/                      | false |
      | https://firefly.reeds.surrey.sch.uk/                   | false |
      | https://www.dublinzoo.ie/                              | false |
      | https://www.mail.theglasgowacademy.org.uk/             | false |
      | https://www.fulhamfc.com/                              | false |
      | https://book-run.disneylandparis.com/                  | false |
      | https://mail.stswithuns.com/                           | false |
      | https://email.handxpark.com/                           | false |
      | https://atvconnection.com/                             | false |
      | https://www.stedmundscollege.org/                      | false |
      | https://webmail.esherhigh.surrey.sch.uk/               | false |
      | https://icon.cumbria.ac.uk/                            | false |
      | https://msexchange.stfrancis.cc/                       | false |
      | https://www.nhm.ac.uk/                                 | false |
      | https://insight.st-mary.blackpool.sch.uk/              | false |
      | https://exchange.kes.hants.sch.uk/                     | false |
      | https://static-nv.mattel.com/                          | false |
      | https://mail.swgs.wilts.sch.uk/                        | false |
      | https://mail.folkestonegirls.kent.sch.uk/              | false |
      | https://account2.lego.com/                             | false |
      | https://www.juventus.com/                              | false |
      | https://insight.salesian.surrey.sch.uk/                | false |
      | https://myhsfc.havering-sfc.ac.uk/                     | false |
      | https://safr.kingfeatures.com/                         | false |
      | https://mail.perins.net/                               | false |
      | https://shop.boys-brigade.org.uk/                      | false |
      | https://www.ccss.co.uk/                                | false |
      | https://exchange.campion.northants.sch.uk/             | false |
      | https://mail.cranford.hounslow.sch.uk/                 | false |
      | https://tickets2.universalorlando.com/                 | false |
      | https://folders.cannockchase-high.staffs.sch.uk/       | false |
      | https://mail.malbank.cheshire.sch.uk/                  | false |
      | https://owa.wolves.co.uk/                              | false |
      | https://www.bramptoncollege.com/                       | false |
      | https://firefly.kings-ely.cambs.sch.uk/                | false |
      | https://mail.ncype.org.uk/                             | false |
      | https://webmail.ardvreck.org.uk/                       | false |
      | https://mansheadschool.co.uk/                          | false |
      | https://mail.culford.co.uk/                            | false |
      | https://m.chester.ac.uk/                               | false |
      | https://outlook.hull-college.ac.uk/                    | false |
      | https://kidskonnect.com/                               | false |
      | https://mail.culchethhigh.org.uk/                      | false |
      | https://www.cumnorhouse.com/                           | false |
      | https://mail.charter.southwark.sch.uk/                 | false |
      | https://www.stnicholasprep.co.uk/                      | false |
      | https://www.royalhighbath.gdst.net/                    | false |
      | https://www.dckids.com/                                | false |
      | https://www.ryestantony.co.uk/                         | false |
      | https://mis-stud.exe-coll.ac.uk/                       | false |
      | https://insight.brookfield.hants.sch.uk/               | false |
      | https://mailx.cityofbristol.ac.uk/                     | false |
      | https://owa.ashville.co.uk/                            | false |
      | https://lego.com/                                      | false |
      | https://www.legoland.dk/                               | false |
      | https://m.wilsonsschool.sutton.sch.uk/                 | false |
      | https://ec1.educationcity.com/                         | false |
      | https://www.holycross.ac.uk/                           | false |
      | https://www.baxtercollege.worcs.sch.uk/                | false |
      | https://sciencebob.com/                                | false |
      | https://mail.greigcityacademy.co.uk/                   | false |
      | https://mail.meopham.kent.sch.uk/                      | false |
      | https://moodle.sfx.ac.uk/                              | false |
      | https://webmail.penryn-college.cornwall.sch.uk/        | false |
      | https://www.gateway.ac.uk/                             | false |
      | https://myportal.wigan-leigh.ac.uk/                    | false |
      | https://www.fromecollege.somerset.sch.uk/              | false |
      | https://www.mtfc.co.uk/                                | false |
      | https://estaticos.alsa.es/                             | false |
      | https://www.stcatherinesarmagh.com/                    | false |
      | https://schoolhistory.co.uk/                           | false |
      | https://www.burntwoodschool.com/                       | false |
      | https://www.kingsbruton.com/                           | false |
      | https://rfsd.cr3.rschooltoday.com/                     | false |
      | https://frog.sherborne.org/                            | false |
      | https://webmail.st-augustines.worcs.sch.uk/            | false |
      | https://www.gdst.net/                                  | false |
      | https://www.morecambefc.com/                           | false |
      | https://secondscreen.mcfc.co.uk/                       | false |
      | https://hibstv.hibernianfc.co.uk/                      | false |
      | https://www.safc.com/                                  | false |
      | https://moodle.cityofbristol.ac.uk/                    | false |
      | https://parents.handxpark.com/                         | false |
      | https://owa.bideford.devon.sch.uk/                     | false |
      | https://email.stgeorges-ascot.org.uk/                  | false |
      | https://www.nesquik.com/                               | false |
      | https://www.rugbyclub-gooi.nl/                         | false |
      | https://tienda.realsociedad.com/                       | false |
      | https://owa.ncgs.co.uk/                                | false |
      | https://mail.damealiceowens.herts.sch.uk/              | false |
      | https://www.owlpages.com/                              | false |
      | https://www.c4ci.com/                                  | false |
      | https://www.alns.co.uk/                                | false |
      | https://onlineshop.dudleyzoo.org.uk/                   | false |
      | https://webmail.stmaryscambridge.co.uk/                | false |
      | https://www.great-chart.kent.sch.uk/                   | false |
      | https://cumnor.co.uk/                                  | false |
      | https://moodle2.colchsfc.ac.uk/                        | false |
      | https://mail.denstonecollege.org/                      | false |
      | https://email.bracknell.ac.uk/                         | false |
      | https://mail.fulford.york.sch.uk/                      | false |
      | https://mail.heathside.surrey.sch.uk/                  | false |
      | https://parentp.epsomcollege.org.uk/                   | false |
      | https://www.emailsanta.com/                            | false |
      | https://mail.waingels.wokingham.sch.uk/                | false |
      | https://www.kingswood.bath.sch.uk/                     | false |
      | https://mail.latymer.co.uk/                            | false |
      | https://webmail.newvic.ac.uk/                          | false |
      | https://vle.exe-coll.ac.uk/                            | false |
      | https://images-galleries.nascar.com/                   | false |
      | https://eportal.monkswalk.herts.sch.uk/                | false |
      | https://www.gshs.org.uk/                               | false |
      | https://mail.holmegrange.org/                          | false |
      | https://owa.westhatch.essex.sch.uk/                    | false |
      | https://www.fullbrook.surrey.sch.uk/                   | false |
      | https://resources.minster.notts.sch.uk/                | false |
      | https://scheduling.rfu.com/                            | false |
      | https://parent.dsfc.ac.uk/                             | false |
      | https://frog.jfk.herts.sch.uk/                         | false |
      | https://www.cfl.ca/                                    | false |
      | https://dehavilland.herts.sch.uk/                      | false |
      | https://webmail.cooperscoborn.org.uk/                  | false |
      | https://www.ripleyaquariums.com/                       | false |
      | https://portal.chellaston.derby.sch.uk/                | false |
      | https://www.fram.durham.sch.uk/                        | false |
      | https://portal.st-augustines.worcs.sch.uk/             | false |
      | https://a2.disneyinternational.com/                    | false |
      | https://moodle.broxbourne.herts.sch.uk/                | false |
      | https://webmail.doverbroecks.com/                      | false |
      | https://blog.sciencemuseum.org.uk/                     | false |
      | https://www.highclareschool.co.uk/                     | false |
      | https://webmail.deanery.wigan.sch.uk/                  | false |
      | https://mail.salesharks.com/                           | false |
      | https://mail.sjl.herts.sch.uk/                         | false |
      | https://www.downsend.co.uk/                            | false |
      | https://services.slingshot.lego.com/                   | false |
      | https://vle.ecclesbourne.derbyshire.sch.uk/            | false |
      | https://lt.global.nba.com/                             | false |
      | https://www.thecobbs.org.uk/                           | false |
      | https://www.hardenhuish.wilts.sch.uk/                  | false |
      | https://sbo.radley.org.uk/                             | false |
      | https://excasvip.princethorpe.co.uk/                   | false |
      | https://www.britishmuseum.org/                         | false |
      | https://mws.chester.ac.uk/                             | false |
      | https://mail.jfs.brent.sch.uk/                         | false |
      | https://our-school.net/                                | false |
      | https://mail2.habsgirls.org.uk/                        | false |
      | https://www.woodrushhigh.worcs.sch.uk/                 | false |
      | https://mail.kingshouseschool.org/                     | false |
      | https://www.ideer.deerparkschool.net/                  | false |
      | https://brudenellprimary.co.uk/                        | false |
      | https://www.southbank.org/                             | false |
      | https://moodle.fromecollege.somerset.sch.uk/           | false |
      | https://sts.gdst.net/                                  | false |
      | https://exchange.helston.cornwall.sch.uk/              | false |
      | https://mail.ursuline.kent.sch.uk/                     | false |
      | https://cs.analytics.lego.com/                         | false |
      | https://mail.jubileehigh.surrey.sch.uk/                | false |
      | https://www.theradclyffeschool.co.uk/                  | false |
      | https://mail.heles.plymouth.sch.uk/                    | false |
      | https://www.harrowway.hants.sch.uk/                    | false |
      | https://obm.boys-brigade.org.uk/                       | false |
      | https://mail.ranelagh.bracknell-forest.sch.uk/         | false |
      | https://static.nascar.com/                             | false |
      | https://help.disney.com/                               | false |
      | https://frog.deanery.wigan.sch.uk/                     | false |
      | https://wiki.kidzsearch.com/                           | false |
      | https://pupils.bloxhamschool.com/                      | false |
      | https://secure.ushmm.org/                              | false |
      | https://web.weaverham.cheshire.sch.uk/                 | false |
      | https://cdn-img.usarugby.org/                          | false |
      | https://www.dkfindout.com/                             | false |
      | https://webmail.poolehigh.poole.sch.uk/                | false |
      | https://components.uwe.ac.uk/                          | false |
      | https://static.mattel.com/                             | false |
      | https://mail.chalfonts.org/                            | false |
      | https://www.musselburghrfc.com/                        | false |
      | https://ilp.lehs.org.uk/                               | false |
      | https://www.keaston.bham.sch.uk/                       | false |
      | https://www.nga.gov/                                   | false |
      | https://tmg.tbshs.herts.sch.uk/                        | false |
      | https://www.orleyfarm.harrow.sch.uk/                   | false |
      | https://www.caldicotschool.com/                        | false |
      | https://isams.brightoncollege.net/                     | false |
      | https://vacations.legoland.com/                        | false |
      | https://www.fairlands.herts.sch.uk/                    | false |
      | https://new.thinkuknow.co.uk/                          | false |
      | https://www.st-andrews.surrey.sch.uk/                  | false |
      | https://moodle.midchesh.ac.uk/                         | false |
      | https://webmail.forest.wokingham.sch.uk/               | false |
      | https://www.st-annes.stockport.sch.uk/                 | false |
      | https://contentdrm.getepic.com/                        | false |
      | https://studentselfservice.rave.ac.uk/                 | false |
      | https://access.christopherwhitehead.worcs.sch.uk/      | false |
      | https://intranet.testvalley.hants.sch.uk/              | false |
      | https://www.linguascope.com/                           | false |
      | https://video.getepic.com/                             | false |
      | https://rds.highdown.reading.sch.uk/                   | false |
      | https://pas.disney.com/                                | false |
      | https://www.nonsuch.sutton.sch.uk/                     | false |
      | https://elearning.bedfordschool.org.uk/                | false |
      | https://webmail.kings.peterborough.sch.uk/             | false |
      | https://webmail.bourne-grammar.lincs.sch.uk/           | false |
      | https://www.warminsterschool.org.uk/                   | false |
      | https://webmail.balcarras.gloucs.sch.uk/               | false |
      | https://resources.scratch.mit.edu/                     | false |
      | https://parentportal.queenswood.org/                   | false |
      | https://mail.chaucer.sheffield.sch.uk/                 | false |
      | https://image.mail.whitehouse.gov/                     | false |
      | https://www.thattoheath.st-helens.sch.uk/              | false |
      | https://www.webkinz.com/                               | false |
      | https://www.perryfieldshigh.sandwell.sch.uk/           | false |
      | https://wasintranet.wycombeabbey.com/                  | false |
      | https://www.olympic.org/                               | false |
      | https://sackville.w-sussex.sch.uk/                     | false |
      | https://webmail.bsix.ac.uk/                            | false |
      | https://mail.bishopstopford.com/                       | false |
      | https://moodle.opgs.org/                               | false |
      | https://www.winterfoldhouse.co.uk/                     | false |
      | https://content.abcmouse.com/                          | false |
      | https://webmail.cherwell.oxon.sch.uk/                  | false |
      | https://qes-web.qehs.lincs.sch.uk/                     | false |
